PRODUCT_COPY_FILES += \
    vendor/sts/a04br3/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/sts/a04br3/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/sts/a04br3/proprietary/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
    vendor/sts/a04br3/proprietary/lib/libMTKAudioTimeStretch.so:system/lib/libMTKAudioTimeStretch.so \
    vendor/sts/a04br3/proprietary/lib/libRS.so:system/lib/libRS.so \
    vendor/sts/a04br3/proprietary/lib/libRSCpuRef.so:system/lib/libRSCpuRef.so \
    vendor/sts/a04br3/proprietary/lib/libRSDriver.so:system/lib/libRSDriver.so \
    vendor/sts/a04br3/proprietary/lib/libRS_internal.so:system/lib/libRS_internal.so \
    vendor/sts/a04br3/proprietary/lib/libRScpp.so:system/lib/libRScpp.so \
    vendor/sts/a04br3/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/sts/a04br3/proprietary/lib/libext2_blkid.so:system/lib/libext2_blkid.so \
    vendor/sts/a04br3/proprietary/lib/libext2_com_err.so:system/lib/libext2_com_err.so \
    vendor/sts/a04br3/proprietary/lib/libext2_e2p.so:system/lib/libext2_e2p.so \
    vendor/sts/a04br3/proprietary/lib/libext2_profile.so:system/lib/libext2_profile.so \
    vendor/sts/a04br3/proprietary/lib/libext2_uuid.so:system/lib/libext2_uuid.so \
    vendor/sts/a04br3/proprietary/lib/libext2fs.so:system/lib/libext2fs.so \
    vendor/sts/a04br3/proprietary/lib/libfs_mgr.so:system/lib/libfs_mgr.so \
    vendor/sts/a04br3/proprietary/lib/libja3m.so:system/lib/libja3m.so \
    vendor/sts/a04br3/proprietary/lib/libjni_eglfence.so:system/lib/libjni_eglfence.so \
    vendor/sts/a04br3/proprietary/lib/libjni_filtershow_filters.so:system/lib/libjni_filtershow_filters.so \
    vendor/sts/a04br3/proprietary/lib/libjni_jpegstream.so:system/lib/libjni_jpegstream.so \
    vendor/sts/a04br3/proprietary/lib/libmediatek_exceptionlog.so:system/lib/libmediatek_exceptionlog.so \
    vendor/sts/a04br3/proprietary/lib/librs_jni.so:system/lib/librs_jni.so \
    vendor/sts/a04br3/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/sts/a04br3/proprietary/lib64/egl/libGLES_android.so:system/lib64/egl/libGLES_android.so \
    vendor/sts/a04br3/proprietary/lib64/hw/audio.usb.default.so:system/lib64/hw/audio.usb.default.so \
    vendor/sts/a04br3/proprietary/lib64/hw/audio_policy.stub.so:system/lib64/hw/audio_policy.stub.so \
    vendor/sts/a04br3/proprietary/lib64/libRS.so:system/lib64/libRS.so \
    vendor/sts/a04br3/proprietary/lib64/libRSCpuRef.so:system/lib64/libRSCpuRef.so \
    vendor/sts/a04br3/proprietary/lib64/libRSDriver.so:system/lib64/libRSDriver.so \
    vendor/sts/a04br3/proprietary/lib64/libRS_internal.so:system/lib64/libRS_internal.so \
    vendor/sts/a04br3/proprietary/lib64/libRScpp.so:system/lib64/libRScpp.so \
    vendor/sts/a04br3/proprietary/lib64/libalsautils.so:system/lib64/libalsautils.so \
    vendor/sts/a04br3/proprietary/lib64/libfs_mgr.so:system/lib64/libfs_mgr.so \
    vendor/sts/a04br3/proprietary/lib64/libja3m.so:system/lib64/libja3m.so \
    vendor/sts/a04br3/proprietary/lib64/libjni_eglfence.so:system/lib64/libjni_eglfence.so \
    vendor/sts/a04br3/proprietary/lib64/libjni_filtershow_filters.so:system/lib64/libjni_filtershow_filters.so \
    vendor/sts/a04br3/proprietary/lib64/libjni_jpegstream.so:system/lib64/libjni_jpegstream.so \
    vendor/sts/a04br3/proprietary/lib64/libmediatek_exceptionlog.so:system/lib64/libmediatek_exceptionlog.so \
    vendor/sts/a04br3/proprietary/lib64/librs_jni.so:system/lib64/librs_jni.so \
    vendor/sts/a04br3/proprietary/lib64/libttscompat.so:system/lib64/libttscompat.so \
    vendor/sts/a04br3/proprietary/lib64/libttspico.so:system/lib64/libttspico.so \
    vendor/sts/a04br3/proprietary/lib64/libxml2.so:system/lib64/libxml2.so \
    vendor/sts/a04br3/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
    vendor/sts/a04br3/proprietary/vendor/bin/MtkCodecService:system/bin/MtkCodecService \
    vendor/sts/a04br3/proprietary/vendor/bin/aee:system/bin/aee \
    vendor/sts/a04br3/proprietary/vendor/bin/aee_archive:system/bin/aee_archive \
    vendor/sts/a04br3/proprietary/vendor/bin/aee_core_forwarder:system/bin/aee_core_forwarder \
    vendor/sts/a04br3/proprietary/vendor/bin/aee_dumpstate:system/bin/aee_dumpstate \
    vendor/sts/a04br3/proprietary/vendor/bin/akmd09911:system/bin/akmd09911 \
    vendor/sts/a04br3/proprietary/vendor/bin/akmd8963:system/bin/akmd8963 \
    vendor/sts/a04br3/proprietary/vendor/bin/akmd8975:system/bin/akmd8975 \
    vendor/sts/a04br3/proprietary/vendor/bin/ami304d:system/bin/ami304d \
    vendor/sts/a04br3/proprietary/vendor/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    vendor/sts/a04br3/proprietary/vendor/bin/autobt:system/bin/autobt \
    vendor/sts/a04br3/proprietary/vendor/bin/autokd:system/bin/autokd \
    vendor/sts/a04br3/proprietary/vendor/bin/bmm050d:system/bin/bmm050d \
    vendor/sts/a04br3/proprietary/vendor/bin/boot_logo_updater:system/bin/boot_logo_updater \
    vendor/sts/a04br3/proprietary/vendor/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/sts/a04br3/proprietary/vendor/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/sts/a04br3/proprietary/vendor/bin/dhcp6c:system/bin/dhcp6c \
    vendor/sts/a04br3/proprietary/vendor/bin/dhcp6ctl:system/bin/dhcp6ctl \
    vendor/sts/a04br3/proprietary/vendor/bin/dhcp6s:system/bin/dhcp6s \
    vendor/sts/a04br3/proprietary/vendor/bin/dmlog:system/bin/dmlog \
    vendor/sts/a04br3/proprietary/vendor/bin/downloader:system/bin/downloader \
    vendor/sts/a04br3/proprietary/vendor/bin/epdg_wod:system/bin/epdg_wod \
    vendor/sts/a04br3/proprietary/vendor/bin/factory:system/bin/factory \
    vendor/sts/a04br3/proprietary/vendor/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
    vendor/sts/a04br3/proprietary/vendor/bin/ged_srv:system/bin/ged_srv \
    vendor/sts/a04br3/proprietary/vendor/bin/gsm0710muxd:system/bin/gsm0710muxd \
    vendor/sts/a04br3/proprietary/vendor/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/sts/a04br3/proprietary/vendor/bin/lcdc_screen_cap:system/bin/lcdc_screen_cap \
    vendor/sts/a04br3/proprietary/vendor/bin/lsm303md:system/bin/lsm303md \
    vendor/sts/a04br3/proprietary/vendor/bin/magd:system/bin/magd \
    vendor/sts/a04br3/proprietary/vendor/bin/matv:system/bin/matv \
    vendor/sts/a04br3/proprietary/vendor/bin/mc6420d:system/bin/mc6420d \
    vendor/sts/a04br3/proprietary/vendor/bin/md_ctrl:system/bin/md_ctrl \
    vendor/sts/a04br3/proprietary/vendor/bin/memorydumper:system/bin/memorydumper \
    vendor/sts/a04br3/proprietary/vendor/bin/memsicd:system/bin/memsicd \
    vendor/sts/a04br3/proprietary/vendor/bin/memsicd3416x:system/bin/memsicd3416x \
    vendor/sts/a04br3/proprietary/vendor/bin/meta_tst:system/bin/meta_tst \
    vendor/sts/a04br3/proprietary/vendor/bin/mobile_log_d:system/bin/mobile_log_d \
    vendor/sts/a04br3/proprietary/vendor/bin/mtkrild:system/bin/mtkrild \
    vendor/sts/a04br3/proprietary/vendor/bin/muxreport:system/bin/muxreport \
    vendor/sts/a04br3/proprietary/vendor/bin/netdiag:system/bin/netdiag \
    vendor/sts/a04br3/proprietary/vendor/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/sts/a04br3/proprietary/vendor/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/sts/a04br3/proprietary/vendor/bin/orientationd:system/bin/orientationd \
    vendor/sts/a04br3/proprietary/vendor/bin/perf_native_test:system/bin/perf_native_test \
    vendor/sts/a04br3/proprietary/vendor/bin/pq:system/bin/pq \
    vendor/sts/a04br3/proprietary/vendor/bin/program_binary_service:system/bin/program_binary_service \
    vendor/sts/a04br3/proprietary/vendor/bin/radvd:system/bin/radvd \
    vendor/sts/a04br3/proprietary/vendor/bin/resize_ext4:system/bin/resize_ext4 \
    vendor/sts/a04br3/proprietary/vendor/bin/rilproxy:system/bin/rilproxy \
    vendor/sts/a04br3/proprietary/vendor/bin/rtt:system/bin/rtt \
    vendor/sts/a04br3/proprietary/vendor/bin/s62xd:system/bin/s62xd \
    vendor/sts/a04br3/proprietary/vendor/bin/slpd:system/bin/slpd \
    vendor/sts/a04br3/proprietary/vendor/bin/stp_dump3:system/bin/stp_dump3 \
    vendor/sts/a04br3/proprietary/vendor/bin/superumount:system/bin/superumount \
    vendor/sts/a04br3/proprietary/vendor/bin/terservice:system/bin/terservice \
    vendor/sts/a04br3/proprietary/vendor/bin/tertestclient:system/bin/tertestclient \
    vendor/sts/a04br3/proprietary/vendor/bin/thermal_manager:system/bin/thermal_manager \
    vendor/sts/a04br3/proprietary/vendor/bin/thermald:system/bin/thermald \
    vendor/sts/a04br3/proprietary/vendor/bin/thermalindicator:system/bin/thermalindicator \
    vendor/sts/a04br3/proprietary/vendor/bin/vtservice:system/bin/vtservice \
    vendor/sts/a04br3/proprietary/vendor/bin/wfca:system/bin/wfca \
    vendor/sts/a04br3/proprietary/vendor/bin/wmt_concurrency:system/bin/wmt_concurrency \
    vendor/sts/a04br3/proprietary/vendor/bin/wmt_launcher:system/bin/wmt_launcher \
    vendor/sts/a04br3/proprietary/vendor/bin/wmt_loader:system/bin/wmt_loader \
    vendor/sts/a04br3/proprietary/vendor/bin/wmt_loopback:system/bin/wmt_loopback \
    vendor/sts/a04br3/proprietary/vendor/etc/.tp/.ht120.mtc:system/etc/.tp/.ht120.mtc \
    vendor/sts/a04br3/proprietary/vendor/etc/.tp/.thermal_policy_00:system/etc/.tp/.thermal_policy_00 \
    vendor/sts/a04br3/proprietary/vendor/etc/.tp/thermal.conf:system/etc/.tp/thermal.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/aee-config:system/etc/aee-config \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_device.xml:system/etc/audio_device.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_em.xml:system/etc/audio_em.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:system/etc/audio_param/AudioParamOptions.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:system/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:system/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:system/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:system/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:system/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:system/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:system/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:system/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:system/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:system/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:system/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:system/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:system/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:system/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:system/etc/audio_param/Playback_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:system/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:system/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:system/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:system/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:system/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:system/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:system/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:system/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:system/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:system/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:system/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:system/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:system/etc/audio_param/Record_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:system/etc/audio_param/Record_ParamTreeView.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:system/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:system/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:system/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:system/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:system/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:system/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:system/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:system/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:system/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:system/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:system/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:system/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:system/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:system/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:system/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:system/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:system/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:system/etc/audio_param/Speech_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:system/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:system/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:system/etc/audio_param/USBCall_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:system/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:system/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:system/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:system/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:system/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:system/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:system/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:system/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:system/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:system/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:system/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:system/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:system/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:system/etc/audio_param/VoIP_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:system/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:system/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:system/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:system/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:system/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:system/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:system/etc/audio_param/Volume_AudioParam.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:system/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/cdma_ecc_list.xml:system/etc/cdma_ecc_list.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/cdma_ecc_list_ss.xml:system/etc/cdma_ecc_list_ss.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/custom.conf:system/etc/custom.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/disableapplist.txt:system/etc/disableapplist.txt \
    vendor/sts/a04br3/proprietary/vendor/etc/ecc_list.xml:system/etc/ecc_list.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/factory.ini:system/etc/factory.ini \
    vendor/sts/a04br3/proprietary/vendor/etc/init/init.wod.rc:system/etc/init/init.wod.rc \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.conf:system/etc/ipsec/ipsec.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:system/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:system/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:system/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:system/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:system/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:system/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:system/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:system/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:system/etc/ipsec/ipsec.d/cacerts/thawte.der \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:system/etc/ipsec/ssl/openssl.cnf \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/strongswan.conf:system/etc/ipsec/strongswan.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/updown_script:system/etc/ipsec/updown_script \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/wod_cust.conf:system/etc/ipsec/wod_cust.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/ipsec/wod_optr.conf:system/etc/ipsec/wod_optr.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
    vendor/sts/a04br3/proprietary/vendor/etc/mtklog-config.prop:system/etc/mtklog-config.prop \
    vendor/sts/a04br3/proprietary/vendor/etc/partition_permission.sh:system/etc/partition_permission.sh \
    vendor/sts/a04br3/proprietary/vendor/etc/perfservscntbl.txt:system/etc/perfservscntbl.txt \
    vendor/sts/a04br3/proprietary/vendor/etc/radvd/radvd.conf:system/etc/radvd/radvd.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/resmonwhitelist.txt:system/etc/resmonwhitelist.txt \
    vendor/sts/a04br3/proprietary/vendor/etc/slp_conf:system/etc/slp_conf \
    vendor/sts/a04br3/proprietary/vendor/etc/throttle.sh:system/etc/throttle.sh \
    vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:system/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:system/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:system/etc/virtual-spn-conf-by-efspn.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:system/etc/virtual-spn-conf-by-imsi.xml \
    vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6c.conf:system/etc/wide-dhcpv6/dhcp6c.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6c.script:system/etc/wide-dhcpv6/dhcp6c.script \
    vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6cDNS.conf:system/etc/wide-dhcpv6/dhcp6cDNS.conf \
    vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6cctlkey:system/etc/wide-dhcpv6/dhcp6cctlkey \
    vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6s.conf:system/etc/wide-dhcpv6/dhcp6s.conf \
    vendor/sts/a04br3/proprietary/vendor/firmware/WIFI_RAM_CODE_MT6630:system/firmware/WIFI_RAM_CODE_MT6630 \
    vendor/sts/a04br3/proprietary/vendor/firmware/WMT.cfg:system/firmware/WMT.cfg \
    vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_ant_m1.cfg:system/firmware/mt6630_ant_m1.cfg \
    vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e1_hdr.bin:system/firmware/mt6630_patch_e1_hdr.bin \
    vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e2_hdr.bin:system/firmware/mt6630_patch_e2_hdr.bin \
    vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e3_0_hdr.bin:system/firmware/mt6630_patch_e3_0_hdr.bin \
    vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e3_1_hdr.bin:system/firmware/mt6630_patch_e3_1_hdr.bin \
    vendor/sts/a04br3/proprietary/vendor/firmware/rgx.fw.signed:system/firmware/rgx.fw.signed \
    vendor/sts/a04br3/proprietary/vendor/firmware/rgx.fw.signed.e1:system/firmware/rgx.fw.signed.e1 \
    vendor/sts/a04br3/proprietary/vendor/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/sts/a04br3/proprietary/vendor/lib/egl/libEGL_mtk.so:system/lib/egl/libEGL_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/lib/egl/libGLESv1_CM_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/lib/egl/libGLESv2_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/lib3a.so:system/lib/lib3a.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libClearMotionFW.so:system/lib/libClearMotionFW.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libGdmaScalerPipe.so:system/lib/libGdmaScalerPipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libIMGegl.so:system/lib/libIMGegl.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libLLVMIMG.so:system/lib/libLLVMIMG.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMiraVision_jni.so:system/lib/libMiraVision_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxVdecEx.so:system/lib/libMtkOmxVdecEx.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libOpenCL.so:system/lib/libOpenCL.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libPQDCjni.so:system/lib/libPQDCjni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libPQjni.so:system/lib/libPQjni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libPVROCL.so:system/lib/libPVROCL.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libPVRScopeServices.so:system/lib/libPVRScopeServices.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libacdk.so:system/lib/libacdk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaed.so:system/lib/libaed.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libamr_wrap.so:system/lib/libamr_wrap.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libamrvt.so:system/lib/libamrvt.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libatvctrlservice.so:system/lib/libatvctrlservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudio_param_parser.so:system/lib/libaudio_param_parser.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudioroute.so:system/lib/libaudioroute.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libaudiotoolkit.so:system/lib/libaudiotoolkit.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libavcodec.so:system/lib/libavcodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libavformat.so:system/lib/libavformat.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libavutil.so:system/lib/libavutil.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libawb_wrap.so:system/lib/libawb_wrap.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_hw_test.so:system/lib/libbluetooth_hw_test.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_mtk_pure.so:system/lib/libbluetooth_mtk_pure.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libbwc.so:system/lib/libbwc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.device3.so:system/lib/libcam.device3.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.exif.v3.so:system/lib/libcam.exif.v3.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.hal3a.v3.dng.so:system/lib/libcam.hal3a.v3.dng.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.hal3a.v3.so:system/lib/libcam.hal3a.v3.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.iopipe_FrmB.so:system/lib/libcam.iopipe_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.metadataprovider.so:system/lib/libcam.metadataprovider.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam.utils.so:system/lib/libcam.utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam3_app.so:system/lib/libcam3_app.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam3_hwnode.so:system/lib/libcam3_hwnode.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam3_hwpipeline.so:system/lib/libcam3_hwpipeline.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam3_pipeline.so:system/lib/libcam3_pipeline.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam3_utils.so:system/lib/libcam3_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcamdrv_FrmB.so:system/lib/libcamdrv_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libccci_util.so:system/lib/libccci_util.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libclangIMG.so:system/lib/libclangIMG.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcomutils.so:system/lib/libcomutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcustom_jni.so:system/lib/libcustom_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libdirect-coredump.so:system/lib/libdirect-coredump.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libfeatureiodrv.so:system/lib/libfeatureiodrv.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libffmpeg_extractor.so:system/lib/libffmpeg_extractor.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libffmpeg_omx.so:system/lib/libffmpeg_omx.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libffmpeg_utils.so:system/lib/libffmpeg_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libfmjni.so:system/lib/libfmjni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libfpspolicy.so:system/lib/libfpspolicy.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libgas.so:system/lib/libgas.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libged.so:system/lib/libged.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libglslcompiler.so:system/lib/libglslcompiler.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libgpu_aux.so:system/lib/libgpu_aux.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libgui_ext.so:system/lib/libgui_ext.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libhdrproc.so:system/lib/libhdrproc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libherope_sa.ca7.so:system/lib/libherope_sa.ca7.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libhevce_sb.ca7.android.so:system/lib/libhevce_sb.ca7.android.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libhwm.so:system/lib/libhwm.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libhwr_u_jni.so:system/lib/libhwr_u_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimageio.so:system/lib/libimageio.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimageio_FrmB.so:system/lib/libimageio_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimageio_plat_drv_FrmB.so:system/lib/libimageio_plat_drv_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimsma.so:system/lib/libimsma.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimsma_rtp.so:system/lib/libimsma_rtp.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libimsma_socketwrapper.so:system/lib/libimsma_socketwrapper.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libjni_pq.so:system/lib/libjni_pq.so \
    vendor/sts/a04br3/proprietary/vendor/lib/liblic_divx.so:system/lib/liblic_divx.so \
    vendor/sts/a04br3/proprietary/vendor/lib/liblic_s263.so:system/lib/liblic_s263.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libm4u.so:system/lib/libm4u.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal.so:system/lib/libmal.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_datamngr.so:system/lib/libmal_datamngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_epdga.so:system/lib/libmal_epdga.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_imsmngr.so:system/lib/libmal_imsmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_mdmngr.so:system/lib/libmal_mdmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_nwmngr.so:system/lib/libmal_nwmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_rds.so:system/lib/libmal_rds.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_rilproxy.so:system/lib/libmal_rilproxy.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmal_simmngr.so:system/lib/libmal_simmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmdfx.so:system/lib/libmdfx.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmemorydumper.so:system/lib/libmemorydumper.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmemtrack_GL.so:system/lib/libmemtrack_GL.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libminiui.so:system/lib/libminiui.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmjcFakeEngine.so:system/lib/libmjcFakeEngine.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmmprofile_jni.so:system/lib/libmmprofile_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmmsdkservice.so:system/lib/libmmsdkservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmrdump.so:system/lib/libmrdump.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtcloader.so:system/lib/libmtcloader.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_service.so:system/lib/libmtk_vt_service.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_swip.so:system/lib/libmtk_vt_swip.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_utils.so:system/lib/libmtk_vt_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_wrapper.so:system/lib/libmtk_vt_wrapper.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtkcam_fwkutils.so:system/lib/libmtkcam_fwkutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libnativecheck-jni.so:system/lib/libnativecheck-jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libnvram.so:system/lib/libnvram.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/sts/a04br3/proprietary/vendor/lib/liboclcompiler.so:system/lib/liboclcompiler.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libperfservice.so:system/lib/libperfservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libpq_cust.so:system/lib/libpq_cust.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libpq_prot.so:system/lib/libpq_prot.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libpqservice.so:system/lib/libpqservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libprogrambinary.so:system/lib/libprogrambinary.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libratconfig.so:system/lib/libratconfig.so \
    vendor/sts/a04br3/proprietary/vendor/lib/librilmtk.so:system/lib/librilmtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib/librilproxy.so:system/lib/librilproxy.so \
    vendor/sts/a04br3/proprietary/vendor/lib/librilproxyutils.so:system/lib/librilproxyutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib/librrc.so:system/lib/librrc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libsbox.so:system/lib/libsbox.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libsink.so:system/lib/libsink.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libsource.so:system/lib/libsource.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libsrv_um.so:system/lib/libsrv_um.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libstorage_otp.so:system/lib/libstorage_otp.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libswresample.so:system/lib/libswresample.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libswscale.so:system/lib/libswscale.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libsysenv.so:system/lib/libsysenv.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libtimestretch.so:system/lib/libtimestretch.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libtouchfilter.so:system/lib/libtouchfilter.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libts.so:system/lib/libts.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libtz_uree.so:system/lib/libtz_uree.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libudf.so:system/lib/libudf.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libufwriter.so:system/lib/libufwriter.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libui_ext.so:system/lib/libui_ext.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libusc.so:system/lib/libusc.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvcodec_cap.so:system/lib/libvcodec_cap.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvoicerecognition.so:system/lib/libvoicerecognition.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvoicerecognition_jni.so:system/lib/libvoicerecognition_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvp8enc_sa.ca7.so:system/lib/libvp8enc_sa.ca7.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvt_avsync.so:system/lib/libvt_avsync.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvt_custom.so:system/lib/libvt_custom.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvt_socketbind.so:system/lib/libvt_socketbind.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libvtmal.so:system/lib/libvtmal.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libwidevinehdcpinfo.so:system/lib/libwidevinehdcpinfo.so \
    vendor/sts/a04br3/proprietary/vendor/lib/libyv12util.so:system/lib/libyv12util.so \
    vendor/sts/a04br3/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/sts/a04br3/proprietary/vendor/lib/mtk-ril.so:system/lib/mtk-ril.so \
    vendor/sts/a04br3/proprietary/vendor/lib/mtk-rilproxy.so:system/lib/mtk-rilproxy.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/egl/libEGL_mtk.so:system/lib64/egl/libEGL_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/egl/libGLESv1_CM_mtk.so:system/lib64/egl/libGLESv1_CM_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/egl/libGLESv2_mtk.so:system/lib64/egl/libGLESv2_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/audio.primary.mt8167.so:system/lib64/hw/audio.primary.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/audio.r_submix.mt8167.so:system/lib64/hw/audio.r_submix.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/audio.usb.mt8167.so:system/lib64/hw/audio.usb.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/gatekeeper.mt8167.so:system/lib64/hw/gatekeeper.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/gralloc.mt8167.so:system/lib64/hw/gralloc.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/hwcomposer.mt8167.so:system/lib64/hw/hwcomposer.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/keystore.mt8167.so:system/lib64/hw/keystore.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/lights.mt8167.so:system/lib64/hw/lights.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/memtrack.mt8167.so:system/lib64/hw/memtrack.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/sensors.mt8167.so:system/lib64/hw/sensors.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/hw/vulkan.mt8167.so:system/lib64/hw/vulkan.mt8167.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/lib3a.so:system/lib64/lib3a.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libBnMtkCodec.so:system/lib64/libBnMtkCodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libGdmaScalerPipe.so:system/lib64/libGdmaScalerPipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libIMGegl.so:system/lib64/libIMGegl.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libJpgDecPipe.so:system/lib64/libJpgDecPipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libLLVMIMG.so:system/lib64/libLLVMIMG.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libMiraVision_jni.so:system/lib64/libMiraVision_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libMtkOmxCore.so:system/lib64/libMtkOmxCore.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libOpenCL.so:system/lib64/libOpenCL.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libPQDCjni.so:system/lib64/libPQDCjni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libPQjni.so:system/lib64/libPQjni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libPVROCL.so:system/lib64/libPVROCL.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libPVRScopeServices.so:system/lib64/libPVRScopeServices.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libSwJpgCodec.so:system/lib64/libSwJpgCodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libacdk.so:system/lib64/libacdk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaed.so:system/lib64/libaed.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libatvctrlservice.so:system/lib64/libatvctrlservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudio_param_parser.so:system/lib64/libaudio_param_parser.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudiocompensationfilter.so:system/lib64/libaudiocompensationfilter.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudiocomponentengine.so:system/lib64/libaudiocomponentengine.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudiocustparam.so:system/lib64/libaudiocustparam.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudiodcrflt.so:system/lib64/libaudiodcrflt.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudioroute.so:system/lib64/libaudioroute.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudiosetting.so:system/lib64/libaudiosetting.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libaudiotoolkit.so:system/lib64/libaudiotoolkit.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libavcodec.so:system/lib64/libavcodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libavformat.so:system/lib64/libavformat.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libavutil.so:system/lib64/libavutil.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbessound_hd_mtk.so:system/lib64/libbessound_hd_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libblisrc.so:system/lib64/libblisrc.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libblisrc32.so:system/lib64/libblisrc32.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_hw_test.so:system/lib64/libbluetooth_hw_test.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_mtk.so:system/lib64/libbluetooth_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_mtk_pure.so:system/lib64/libbluetooth_mtk_pure.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_relayer.so:system/lib64/libbluetooth_relayer.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbluetoothem_mtk.so:system/lib64/libbluetoothem_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libbwc.so:system/lib64/libbwc.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.campipe.so:system/lib64/libcam.campipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.client.so:system/lib64/libcam.client.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.device3.so:system/lib64/libcam.device3.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.exif.v3.so:system/lib64/libcam.exif.v3.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.hal3a.v3.dng.so:system/lib64/libcam.hal3a.v3.dng.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.hal3a.v3.so:system/lib64/libcam.hal3a.v3.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.halsensor.so:system/lib64/libcam.halsensor.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.iopipe.so:system/lib64/libcam.iopipe.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.iopipe_FrmB.so:system/lib64/libcam.iopipe_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.metadataprovider.so:system/lib64/libcam.metadataprovider.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.utils.sensorlistener.so:system/lib64/libcam.utils.sensorlistener.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam.utils.so:system/lib64/libcam.utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_app.so:system/lib64/libcam3_app.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_hwnode.so:system/lib64/libcam3_hwnode.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_hwpipeline.so:system/lib64/libcam3_hwpipeline.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_pipeline.so:system/lib64/libcam3_pipeline.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_utils.so:system/lib64/libcam3_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcamdrv_FrmB.so:system/lib64/libcamdrv_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libccci_util.so:system/lib64/libccci_util.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libclangIMG.so:system/lib64/libclangIMG.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcomutils.so:system/lib64/libcomutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcustom_jni.so:system/lib64/libcustom_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcustom_nvram.so:system/lib64/libcustom_nvram.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcustom_prop.so:system/lib64/libcustom_prop.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libcvsd_mtk.so:system/lib64/libcvsd_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libdirect-coredump.so:system/lib64/libdirect-coredump.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libdpframework.so:system/lib64/libdpframework.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libfeatureio.so:system/lib64/libfeatureio.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libfeatureiodrv.so:system/lib64/libfeatureiodrv.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libffmpeg_extractor.so:system/lib64/libffmpeg_extractor.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libffmpeg_omx.so:system/lib64/libffmpeg_omx.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libffmpeg_utils.so:system/lib64/libffmpeg_utils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libfile_op.so:system/lib64/libfile_op.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libfmjni.so:system/lib64/libfmjni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libfpspolicy.so:system/lib64/libfpspolicy.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libgas.so:system/lib64/libgas.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libged.so:system/lib64/libged.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libglslcompiler.so:system/lib64/libglslcompiler.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libgpu_aux.so:system/lib64/libgpu_aux.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libgralloc_extra.so:system/lib64/libgralloc_extra.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libgui_ext.so:system/lib64/libgui_ext.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libhdrproc.so:system/lib64/libhdrproc.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libhwm.so:system/lib64/libhwm.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libhwr_u_jni.so:system/lib64/libhwr_u_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimageio.so:system/lib64/libimageio.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimageio_FrmB.so:system/lib64/libimageio_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimageio_plat_drv_FrmB.so:system/lib64/libimageio_plat_drv_FrmB.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimsma.so:system/lib64/libimsma.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimsma_rtp.so:system/lib64/libimsma_rtp.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libimsma_socketwrapper.so:system/lib64/libimsma_socketwrapper.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libion_mtk.so:system/lib64/libion_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libjni_pq.so:system/lib64/libjni_pq.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libm4u.so:system/lib64/libm4u.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal.so:system/lib64/libmal.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_datamngr.so:system/lib64/libmal_datamngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_epdga.so:system/lib64/libmal_epdga.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_imsmngr.so:system/lib64/libmal_imsmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_mdmngr.so:system/lib64/libmal_mdmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_nwmngr.so:system/lib64/libmal_nwmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_rds.so:system/lib64/libmal_rds.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_rilproxy.so:system/lib64/libmal_rilproxy.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmal_simmngr.so:system/lib64/libmal_simmngr.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmdfx.so:system/lib64/libmdfx.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmemorydumper.so:system/lib64/libmemorydumper.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmemtrack_GL.so:system/lib64/libmemtrack_GL.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmhalImageCodec.so:system/lib64/libmhalImageCodec.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libminiui.so:system/lib64/libminiui.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmmprofile.so:system/lib64/libmmprofile.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmmprofile_jni.so:system/lib64/libmmprofile_jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmrdump.so:system/lib64/libmrdump.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmsbc_mtk.so:system/lib64/libmsbc_mtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtk_mmutils.so:system/lib64/libmtk_mmutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtk_vt_wrapper.so:system/lib64/libmtk_vt_wrapper.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtkcam_fwkutils.so:system/lib64/libmtkcam_fwkutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtkjpeg.so:system/lib64/libmtkjpeg.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtkplayer.so:system/lib64/libmtkplayer.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libnativecheck-jni.so:system/lib64/libnativecheck-jni.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libnvram.so:system/lib64/libnvram.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libnvram_daemon_callback.so:system/lib64/libnvram_daemon_callback.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libnvram_platform.so:system/lib64/libnvram_platform.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libnvram_sec.so:system/lib64/libnvram_sec.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libnvramagentclient.so:system/lib64/libnvramagentclient.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/liboclcompiler.so:system/lib64/liboclcompiler.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libperfservice.so:system/lib64/libperfservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libperfservicenative.so:system/lib64/libperfservicenative.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libpq_cust.so:system/lib64/libpq_cust.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libpq_prot.so:system/lib64/libpq_prot.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libpqservice.so:system/lib64/libpqservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libprogrambinary.so:system/lib64/libprogrambinary.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libpvrANDROID_WSEGL.so:system/lib64/libpvrANDROID_WSEGL.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libratconfig.so:system/lib64/libratconfig.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/librilmtk.so:system/lib64/librilmtk.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/librilproxy.so:system/lib64/librilproxy.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/librilproxyutils.so:system/lib64/librilproxyutils.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/librrc.so:system/lib64/librrc.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libsbox.so:system/lib64/libsbox.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libsink.so:system/lib64/libsink.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libsource.so:system/lib64/libsource.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libspeech_enh_lib.so:system/lib64/libspeech_enh_lib.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libsrv_um.so:system/lib64/libsrv_um.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libswresample.so:system/lib64/libswresample.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libswscale.so:system/lib64/libswscale.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libsysenv.so:system/lib64/libsysenv.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libterservice.so:system/lib64/libterservice.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libtouchfilter.so:system/lib64/libtouchfilter.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libts.so:system/lib64/libts.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libtz_uree.so:system/lib64/libtz_uree.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libudf.so:system/lib64/libudf.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libufwriter.so:system/lib64/libufwriter.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libui_ext.so:system/lib64/libui_ext.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libusc.so:system/lib64/libusc.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libvcodec_cap.so:system/lib64/libvcodec_cap.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libvcodec_utility.so:system/lib64/libvcodec_utility.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libvcodecdrv.so:system/lib64/libvcodecdrv.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libvt_avsync.so:system/lib64/libvt_avsync.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libwidevinehdcpinfo.so:system/lib64/libwidevinehdcpinfo.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/libyv12util.so:system/lib64/libyv12util.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/mtk-ril.so:system/lib64/mtk-ril.so \
    vendor/sts/a04br3/proprietary/vendor/lib64/mtk-rilproxy.so:system/lib64/mtk-rilproxy.so
