PRODUCT_COPY_FILES += \
vendor/sts/a04br3/proprietary/framework/arm/boot-mediatek-common.art:system/framework/arm/boot-mediatek-common.art \
vendor/sts/a04br3/proprietary/framework/arm/boot-mediatek-common.oat:system/framework/arm/boot-mediatek-common.oat \
vendor/sts/a04br3/proprietary/framework/arm/boot-mediatek-framework.art:system/framework/arm/boot-mediatek-framework.art \
vendor/sts/a04br3/proprietary/framework/arm/boot-mediatek-framework.oat:system/framework/arm/boot-mediatek-framework.oat \
vendor/sts/a04br3/proprietary/framework/arm/boot-mediatek-telephony-common.art:system/framework/arm/boot-mediatek-telephony-common.art \
vendor/sts/a04br3/proprietary/framework/arm/boot-mediatek-telephony-common.oat:system/framework/arm/boot-mediatek-telephony-common.oat \
vendor/sts/a04br3/proprietary/framework/arm64/boot-mediatek-common.art:system/framework/arm64/boot-mediatek-common.art \
vendor/sts/a04br3/proprietary/framework/arm64/boot-mediatek-common.oat:system/framework/arm64/boot-mediatek-common.oat \
vendor/sts/a04br3/proprietary/framework/arm64/boot-mediatek-framework.art:system/framework/arm64/boot-mediatek-framework.art \
vendor/sts/a04br3/proprietary/framework/arm64/boot-mediatek-framework.oat:system/framework/arm64/boot-mediatek-framework.oat \
vendor/sts/a04br3/proprietary/framework/arm64/boot-mediatek-telephony-common.art:system/framework/arm64/boot-mediatek-telephony-common.art \
vendor/sts/a04br3/proprietary/framework/arm64/boot-mediatek-telephony-common.oat:system/framework/arm64/boot-mediatek-telephony-common.oat \
vendor/sts/a04br3/proprietary/framework/mediatek-common.jar:system/framework/mediatek-common.jar \
vendor/sts/a04br3/proprietary/framework/mediatek-framework.jar:system/framework/mediatek-framework.jar \
vendor/sts/a04br3/proprietary/framework/mediatek-telephony-common.jar:system/framework/mediatek-telephony-common.jar \
vendor/sts/a04br3/proprietary/etc/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
vendor/sts/a04br3/proprietary/etc/media_codecs_google_video_le.xml:system/etc/media_codecs_google_video_le.xml \
vendor/sts/a04br3/proprietary/etc/media_codecs_mediatek_audio.xml:system/etc/media_codecs_mediatek_audio.xml \
vendor/sts/a04br3/proprietary/etc/media_codecs_mediatek_video.xml:system/etc/media_codecs_mediatek_video.xml \
vendor/sts/a04br3/proprietary/lib/libmediatek_exceptionlog.so:system/lib/libmediatek_exceptionlog.so \
vendor/sts/a04br3/proprietary/lib/libMTKAudioTimeStretch.so:system/lib/libMTKAudioTimeStretch.so \
vendor/sts/a04br3/proprietary/lib64/libconscrypt_gmscore_jni.so:system/lib64/libconscrypt_gmscore_jni.so \
vendor/sts/a04br3/proprietary/lib64/libgmscore.so:system/lib64/libgmscore.so \
vendor/sts/a04br3/proprietary/lib64/libgoogle-ocrclient-v3.so:system/lib64/libgoogle-ocrclient-v3.so \
vendor/sts/a04br3/proprietary/lib64/libmediatek_exceptionlog.so:system/lib64/libmediatek_exceptionlog.so \
vendor/sts/a04br3/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
vendor/sts/a04br3/proprietary/vendor/app/BtTool/BtTool.apk:system/vendor/app/BtTool/BtTool.apk \
vendor/sts/a04br3/proprietary/vendor/app/BtTool/oat/arm64/BtTool.odex:system/vendor/app/BtTool/oat/arm64/BtTool.odex \
vendor/sts/a04br3/proprietary/vendor/app/CalendarImporter/CalendarImporter.apk:system/vendor/app/CalendarImporter/CalendarImporter.apk \
vendor/sts/a04br3/proprietary/vendor/app/CalendarImporter/oat/arm64/CalendarImporter.odex:system/vendor/app/CalendarImporter/oat/arm64/CalendarImporter.odex \
vendor/sts/a04br3/proprietary/vendor/app/Camera/Camera.apk:system/vendor/app/Camera/Camera.apk \
vendor/sts/a04br3/proprietary/vendor/app/Camera/oat/arm64/Camera.odex:system/vendor/app/Camera/oat/arm64/Camera.odex \
vendor/sts/a04br3/proprietary/vendor/app/MtkBrowser/MtkBrowser.apk:system/vendor/app/MtkBrowser/MtkBrowser.apk \
vendor/sts/a04br3/proprietary/vendor/app/MtkBrowser/oat/arm64/MtkBrowser.odex:system/vendor/app/MtkBrowser/oat/arm64/MtkBrowser.odex \
vendor/sts/a04br3/proprietary/vendor/app/MtkCalendar/MtkCalendar.apk:system/vendor/app/MtkCalendar/MtkCalendar.apk \
vendor/sts/a04br3/proprietary/vendor/app/MtkCalendar/oat/arm64/MtkCalendar.odex:system/vendor/app/MtkCalendar/oat/arm64/MtkCalendar.odex \
vendor/sts/a04br3/proprietary/vendor/app/MTKLogger/MTKLogger.apk:system/vendor/app/MTKLogger/MTKLogger.apk \
vendor/sts/a04br3/proprietary/vendor/app/MTKLogger/oat/arm64/MTKLogger.odex:system/vendor/app/MTKLogger/oat/arm64/MTKLogger.odex \
vendor/sts/a04br3/proprietary/vendor/app/MTKThermalManager/MTKThermalManager.apk:system/vendor/app/MTKThermalManager/MTKThermalManager.apk \
vendor/sts/a04br3/proprietary/vendor/app/MTKThermalManager/oat/arm64/MTKThermalManager.odex:system/vendor/app/MTKThermalManager/oat/arm64/MTKThermalManager.odex \
vendor/sts/a04br3/proprietary/vendor/app/Music/Music.apk:system/vendor/app/Music/Music.apk \
vendor/sts/a04br3/proprietary/vendor/app/Music/oat/arm64/Music.odex:system/vendor/app/Music/oat/arm64/Music.odex \
vendor/sts/a04br3/proprietary/vendor/bin/aee:system/vendor/bin/aee \
vendor/sts/a04br3/proprietary/vendor/bin/aee_archive:system/vendor/bin/aee_archive \
vendor/sts/a04br3/proprietary/vendor/bin/aee_core_forwarder:system/vendor/bin/aee_core_forwarder \
vendor/sts/a04br3/proprietary/vendor/bin/aee_dumpstate:system/vendor/bin/aee_dumpstate \
vendor/sts/a04br3/proprietary/vendor/bin/akmd09911:system/vendor/bin/akmd09911 \
vendor/sts/a04br3/proprietary/vendor/bin/akmd8963:system/vendor/bin/akmd8963 \
vendor/sts/a04br3/proprietary/vendor/bin/akmd8975:system/vendor/bin/akmd8975 \
vendor/sts/a04br3/proprietary/vendor/bin/ami304d:system/vendor/bin/ami304d \
vendor/sts/a04br3/proprietary/vendor/bin/audiocmdservice_atci:system/vendor/bin/audiocmdservice_atci \
vendor/sts/a04br3/proprietary/vendor/bin/autobt:system/vendor/bin/autobt \
vendor/sts/a04br3/proprietary/vendor/bin/autokd:system/vendor/bin/autokd \
vendor/sts/a04br3/proprietary/vendor/bin/bmm050d:system/vendor/bin/bmm050d \
vendor/sts/a04br3/proprietary/vendor/bin/boot_logo_updater:system/vendor/bin/boot_logo_updater \
vendor/sts/a04br3/proprietary/vendor/bin/ccci_fsd:system/vendor/bin/ccci_fsd \
vendor/sts/a04br3/proprietary/vendor/bin/ccci_mdinit:system/vendor/bin/ccci_mdinit \
vendor/sts/a04br3/proprietary/vendor/bin/dhcp6c:system/vendor/bin/dhcp6c \
vendor/sts/a04br3/proprietary/vendor/bin/dhcp6ctl:system/vendor/bin/dhcp6ctl \
vendor/sts/a04br3/proprietary/vendor/bin/dhcp6s:system/vendor/bin/dhcp6s \
vendor/sts/a04br3/proprietary/vendor/bin/dmlog:system/vendor/bin/dmlog \
vendor/sts/a04br3/proprietary/vendor/bin/downloader:system/vendor/bin/downloader \
vendor/sts/a04br3/proprietary/vendor/bin/epdg_wod:system/vendor/bin/epdg_wod \
vendor/sts/a04br3/proprietary/vendor/bin/factory:system/vendor/bin/factory \
vendor/sts/a04br3/proprietary/vendor/bin/fsck_msdos_mtk:system/vendor/bin/fsck_msdos_mtk \
vendor/sts/a04br3/proprietary/vendor/bin/ged_srv:system/vendor/bin/ged_srv \
vendor/sts/a04br3/proprietary/vendor/bin/gsm0710muxd:system/vendor/bin/gsm0710muxd \
vendor/sts/a04br3/proprietary/vendor/bin/kisd:system/vendor/bin/kisd \
vendor/sts/a04br3/proprietary/vendor/bin/kpoc_charger:system/vendor/bin/kpoc_charger \
vendor/sts/a04br3/proprietary/vendor/bin/lcdc_screen_cap:system/vendor/bin/lcdc_screen_cap \
vendor/sts/a04br3/proprietary/vendor/bin/lsm303md:system/vendor/bin/lsm303md \
vendor/sts/a04br3/proprietary/vendor/bin/magd:system/vendor/bin/magd \
vendor/sts/a04br3/proprietary/vendor/bin/matv:system/vendor/bin/matv \
vendor/sts/a04br3/proprietary/vendor/bin/mc6420d:system/vendor/bin/mc6420d \
vendor/sts/a04br3/proprietary/vendor/bin/md_ctrl:system/vendor/bin/md_ctrl \
vendor/sts/a04br3/proprietary/vendor/bin/memorydumper:system/vendor/bin/memorydumper \
vendor/sts/a04br3/proprietary/vendor/bin/memsicd3416x:system/vendor/bin/memsicd3416x \
vendor/sts/a04br3/proprietary/vendor/bin/memsicd:system/vendor/bin/memsicd \
vendor/sts/a04br3/proprietary/vendor/bin/meta_tst:system/vendor/bin/meta_tst \
vendor/sts/a04br3/proprietary/vendor/bin/mobile_log_d:system/vendor/bin/mobile_log_d \
vendor/sts/a04br3/proprietary/vendor/bin/MtkCodecService:system/vendor/bin/MtkCodecService \
vendor/sts/a04br3/proprietary/vendor/bin/mtkrild:system/vendor/bin/mtkrild \
vendor/sts/a04br3/proprietary/vendor/bin/muxreport:system/vendor/bin/muxreport \
vendor/sts/a04br3/proprietary/vendor/bin/netdiag:system/vendor/bin/netdiag \
vendor/sts/a04br3/proprietary/vendor/bin/nvram_agent_binder:system/vendor/bin/nvram_agent_binder \
vendor/sts/a04br3/proprietary/vendor/bin/nvram_daemon:system/vendor/bin/nvram_daemon \
vendor/sts/a04br3/proprietary/vendor/bin/orientationd:system/vendor/bin/orientationd \
vendor/sts/a04br3/proprietary/vendor/bin/perf_native_test:system/vendor/bin/perf_native_test \
vendor/sts/a04br3/proprietary/vendor/bin/pq:system/vendor/bin/pq \
vendor/sts/a04br3/proprietary/vendor/bin/program_binary_builder:system/vendor/bin/program_binary_builder \
vendor/sts/a04br3/proprietary/vendor/bin/program_binary_service:system/vendor/bin/program_binary_service \
vendor/sts/a04br3/proprietary/vendor/bin/radvd:system/vendor/bin/radvd \
vendor/sts/a04br3/proprietary/vendor/bin/resize_ext4:system/vendor/bin/resize_ext4 \
vendor/sts/a04br3/proprietary/vendor/bin/rilproxy:system/vendor/bin/rilproxy \
vendor/sts/a04br3/proprietary/vendor/bin/rpmb_svc:system/vendor/bin/rpmb_svc \
vendor/sts/a04br3/proprietary/vendor/bin/rtt:system/vendor/bin/rtt \
vendor/sts/a04br3/proprietary/vendor/bin/s62xd:system/vendor/bin/s62xd \
vendor/sts/a04br3/proprietary/vendor/bin/slpd:system/vendor/bin/slpd \
vendor/sts/a04br3/proprietary/vendor/bin/stp_dump3:system/vendor/bin/stp_dump3 \
vendor/sts/a04br3/proprietary/vendor/bin/superumount:system/vendor/bin/superumount \
vendor/sts/a04br3/proprietary/vendor/bin/terservice:system/vendor/bin/terservice \
vendor/sts/a04br3/proprietary/vendor/bin/tertestclient:system/vendor/bin/tertestclient \
vendor/sts/a04br3/proprietary/vendor/bin/thermal:system/vendor/bin/thermal \
vendor/sts/a04br3/proprietary/vendor/bin/thermal_manager:system/vendor/bin/thermal_manager \
vendor/sts/a04br3/proprietary/vendor/bin/thermald:system/vendor/bin/thermald \
vendor/sts/a04br3/proprietary/vendor/bin/thermalindicator:system/vendor/bin/thermalindicator \
vendor/sts/a04br3/proprietary/vendor/bin/tiny_mkswap:system/vendor/bin/tiny_mkswap \
vendor/sts/a04br3/proprietary/vendor/bin/tiny_swapoff:system/vendor/bin/tiny_swapoff \
vendor/sts/a04br3/proprietary/vendor/bin/tiny_swapon:system/vendor/bin/tiny_swapon \
vendor/sts/a04br3/proprietary/vendor/bin/vtservice:system/vendor/bin/vtservice \
vendor/sts/a04br3/proprietary/vendor/bin/wfbt_wr:system/vendor/bin/wfbt_wr \
vendor/sts/a04br3/proprietary/vendor/bin/wfca:system/vendor/bin/wfca \
vendor/sts/a04br3/proprietary/vendor/bin/wmt_concurrency:system/vendor/bin/wmt_concurrency \
vendor/sts/a04br3/proprietary/vendor/bin/wmt_launcher:system/vendor/bin/wmt_launcher \
vendor/sts/a04br3/proprietary/vendor/bin/wmt_loader:system/vendor/bin/wmt_loader \
vendor/sts/a04br3/proprietary/vendor/bin/wmt_loopback:system/vendor/bin/wmt_loopback \
vendor/sts/a04br3/proprietary/vendor/bin/XoSetCap:system/vendor/bin/XoSetCap \
vendor/sts/a04br3/proprietary/vendor/data/misc/ProjectConfig.mk:system/vendor/data/misc/ProjectConfig.mk \
vendor/sts/a04br3/proprietary/vendor/etc/.tp/.ht120.mtc:system/vendor/etc/.tp/.ht120.mtc \
vendor/sts/a04br3/proprietary/vendor/etc/.tp/.thermal_policy_00:system/vendor/etc/.tp/.thermal_policy_00 \
vendor/sts/a04br3/proprietary/vendor/etc/.tp/thermal.conf:system/vendor/etc/.tp/thermal.conf \
vendor/sts/a04br3/proprietary/vendor/etc/aee-config:system/vendor/etc/aee-config \
vendor/sts/a04br3/proprietary/vendor/etc/appwidget/3dwidgets.xml:system/vendor/etc/appwidget/3dwidgets.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_device.xml:system/vendor/etc/audio_device.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_em.xml:system/vendor/etc/audio_em.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:system/vendor/etc/audio_param/AudioParamOptions.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:system/vendor/etc/audio_param/BtInfo_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:system/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:system/vendor/etc/audio_param/Playback_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:system/vendor/etc/audio_param/Playback_ParamTreeView.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:system/vendor/etc/audio_param/Playback_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:system/vendor/etc/audio_param/PlaybackACF_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:system/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:system/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:system/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:system/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:system/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:system/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:system/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:system/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:system/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:system/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:system/vendor/etc/audio_param/Record_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:system/vendor/etc/audio_param/Record_ParamTreeView.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:system/vendor/etc/audio_param/Record_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:system/vendor/etc/audio_param/RecordDMNR_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:system/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:system/vendor/etc/audio_param/RecordFIR_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:system/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:system/vendor/etc/audio_param/RecordUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:system/vendor/etc/audio_param/RecordVol_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:system/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:system/vendor/etc/audio_param/RecordVolUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:system/vendor/etc/audio_param/Speech_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:system/vendor/etc/audio_param/Speech_ParamTreeView.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:system/vendor/etc/audio_param/Speech_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:system/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:system/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:system/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:system/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:system/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:system/vendor/etc/audio_param/SpeechUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:system/vendor/etc/audio_param/SpeechVol_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:system/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:system/vendor/etc/audio_param/USBCall_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:system/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:system/vendor/etc/audio_param/USBDevice_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:system/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:system/vendor/etc/audio_param/VoIP_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:system/vendor/etc/audio_param/VoIP_ParamTreeView.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:system/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:system/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:system/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:system/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:system/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:system/vendor/etc/audio_param/VoIPUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:system/vendor/etc/audio_param/VoIPVol_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:system/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:system/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:system/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:system/vendor/etc/audio_param/Volume_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:system/vendor/etc/audio_param/Volume_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:system/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:system/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:system/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:system/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
vendor/sts/a04br3/proprietary/vendor/etc/audio_policy.conf:system/vendor/etc/audio_policy.conf \
vendor/sts/a04br3/proprietary/vendor/etc/cdma_ecc_list.xml:system/vendor/etc/cdma_ecc_list.xml \
vendor/sts/a04br3/proprietary/vendor/etc/cdma_ecc_list_ss.xml:system/vendor/etc/cdma_ecc_list_ss.xml \
vendor/sts/a04br3/proprietary/vendor/etc/custom.conf:system/vendor/etc/custom.conf \
vendor/sts/a04br3/proprietary/vendor/etc/disableapplist.txt:system/vendor/etc/disableapplist.txt \
vendor/sts/a04br3/proprietary/vendor/etc/ecc_list.xml:system/vendor/etc/ecc_list.xml \
vendor/sts/a04br3/proprietary/vendor/etc/factory.ini:system/vendor/etc/factory.ini \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Drm/Gallery2Drm.apk:system/vendor/etc/gallery/Gallery2Drm/Gallery2Drm.apk \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Gif/Gallery2Gif.apk:system/vendor/etc/gallery/Gallery2Gif/Gallery2Gif.apk \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Gif/oat/arm64/Gallery2Gif.odex:system/vendor/etc/gallery/Gallery2Gif/oat/arm64/Gallery2Gif.odex \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Pq/Gallery2Pq.apk:system/vendor/etc/gallery/Gallery2Pq/Gallery2Pq.apk \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Pq/oat/arm64/Gallery2Pq.odex:system/vendor/etc/gallery/Gallery2Pq/oat/arm64/Gallery2Pq.odex \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2PqTool/Gallery2PqTool.apk:system/vendor/etc/gallery/Gallery2PqTool/Gallery2PqTool.apk \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2PqTool/oat/arm64/Gallery2PqTool.odex:system/vendor/etc/gallery/Gallery2PqTool/oat/arm64/Gallery2PqTool.odex \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Raw/Gallery2Raw.apk:system/vendor/etc/gallery/Gallery2Raw/Gallery2Raw.apk \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Raw/oat/arm64/Gallery2Raw.odex:system/vendor/etc/gallery/Gallery2Raw/oat/arm64/Gallery2Raw.odex \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Root/Gallery2Root.apk:system/vendor/etc/gallery/Gallery2Root/Gallery2Root.apk \
vendor/sts/a04br3/proprietary/vendor/etc/gallery/Gallery2Root/oat/arm64/Gallery2Root.odex:system/vendor/etc/gallery/Gallery2Root/oat/arm64/Gallery2Root.odex \
vendor/sts/a04br3/proprietary/vendor/etc/init/init.wod.rc:system/vendor/etc/init/init.wod.rc \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.conf:system/vendor/etc/ipsec/ipsec.conf \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:system/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:system/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:system/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:system/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:system/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:system/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:system/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:system/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:system/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:system/vendor/etc/ipsec/ssl/openssl.cnf \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/strongswan.conf:system/vendor/etc/ipsec/strongswan.conf \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/updown_script:system/vendor/etc/ipsec/updown_script \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/wod_cust.conf:system/vendor/etc/ipsec/wod_cust.conf \
vendor/sts/a04br3/proprietary/vendor/etc/ipsec/wod_optr.conf:system/vendor/etc/ipsec/wod_optr.conf \
vendor/sts/a04br3/proprietary/vendor/etc/mixer_paths.xml:system/vendor/etc/mixer_paths.xml \
vendor/sts/a04br3/proprietary/vendor/etc/mtk_omx_core.cfg:system/vendor/etc/mtk_omx_core.cfg \
vendor/sts/a04br3/proprietary/vendor/etc/mtklog-config.prop:system/vendor/etc/mtklog-config.prop \
vendor/sts/a04br3/proprietary/vendor/etc/partition_permission.sh:system/vendor/etc/partition_permission.sh \
vendor/sts/a04br3/proprietary/vendor/etc/perfservscntbl.txt:system/vendor/etc/perfservscntbl.txt \
vendor/sts/a04br3/proprietary/vendor/etc/perfservtouchfilter.txt:system/vendor/etc/perfservtouchfilter.txt \
vendor/sts/a04br3/proprietary/vendor/etc/public.libraries.txt:system/vendor/etc/public.libraries.txt \
vendor/sts/a04br3/proprietary/vendor/etc/radvd/radvd.conf:system/vendor/etc/radvd/radvd.conf \
vendor/sts/a04br3/proprietary/vendor/etc/recovery.fstab:system/vendor/etc/recovery.fstab \
vendor/sts/a04br3/proprietary/vendor/etc/resmonwhitelist.txt:system/vendor/etc/resmonwhitelist.txt \
vendor/sts/a04br3/proprietary/vendor/etc/slp_conf:system/vendor/etc/slp_conf \
vendor/sts/a04br3/proprietary/vendor/etc/throttle.sh:system/vendor/etc/throttle.sh \
vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:system/vendor/etc/virtual-spn-conf-by-efgid1.xml \
vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:system/vendor/etc/virtual-spn-conf-by-efpnn.xml \
vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:system/vendor/etc/virtual-spn-conf-by-efspn.xml \
vendor/sts/a04br3/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:system/vendor/etc/virtual-spn-conf-by-imsi.xml \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/1.pcm:system/vendor/etc/voicecommand/training/ubmfile/1.pcm \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/128.dat:system/vendor/etc/voicecommand/training/ubmfile/128.dat \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/2.pcm:system/vendor/etc/voicecommand/training/ubmfile/2.pcm \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/3.pcm:system/vendor/etc/voicecommand/training/ubmfile/3.pcm \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/4.pcm:system/vendor/etc/voicecommand/training/ubmfile/4.pcm \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/64.dat:system/vendor/etc/voicecommand/training/ubmfile/64.dat \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.f:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.f \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.gen:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.gen \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.l:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.l \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.p:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.p \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.t:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/c_e_dic.bin.t \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/commandfilr3.dic:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/commandfilr3.dic \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model1.bin:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model1.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model4.bin:system/vendor/etc/voicecommand/training/ubmfile/antiCmds/Model4.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/nl:system/vendor/etc/voicecommand/training/ubmfile/nl \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/ubmModel0.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel0.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/ubmModel1.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel1.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/ubmModel10.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel10.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/ubmModel2.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel2.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/ubmModel3.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel3.bin \
vendor/sts/a04br3/proprietary/vendor/etc/voicecommand/training/ubmfile/ubmModel4.bin:system/vendor/etc/voicecommand/training/ubmfile/ubmModel4.bin \
vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6c.conf:system/vendor/etc/wide-dhcpv6/dhcp6c.conf \
vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6c.script:system/vendor/etc/wide-dhcpv6/dhcp6c.script \
vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6cctlkey:system/vendor/etc/wide-dhcpv6/dhcp6cctlkey \
vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6cDNS.conf:system/vendor/etc/wide-dhcpv6/dhcp6cDNS.conf \
vendor/sts/a04br3/proprietary/vendor/etc/wide-dhcpv6/dhcp6s.conf:system/vendor/etc/wide-dhcpv6/dhcp6s.conf \
vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_ant_m1.cfg:system/vendor/firmware/mt6630_ant_m1.cfg \
vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e1_hdr.bin:system/vendor/firmware/mt6630_patch_e1_hdr.bin \
vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e2_hdr.bin:system/vendor/firmware/mt6630_patch_e2_hdr.bin \
vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e3_0_hdr.bin:system/vendor/firmware/mt6630_patch_e3_0_hdr.bin \
vendor/sts/a04br3/proprietary/vendor/firmware/mt6630_patch_e3_1_hdr.bin:system/vendor/firmware/mt6630_patch_e3_1_hdr.bin \
vendor/sts/a04br3/proprietary/vendor/firmware/rgx.fw.signed.e1:system/vendor/firmware/rgx.fw.signed.e1 \
vendor/sts/a04br3/proprietary/vendor/firmware/rgx.fw.signed:system/vendor/firmware/rgx.fw.signed \
vendor/sts/a04br3/proprietary/vendor/firmware/WIFI_RAM_CODE_MT6630:system/vendor/firmware/WIFI_RAM_CODE_MT6630 \
vendor/sts/a04br3/proprietary/vendor/firmware/WMT.cfg:system/vendor/firmware/WMT.cfg \
vendor/sts/a04br3/proprietary/vendor/framework/CustomPropInterface.jar:system/vendor/framework/CustomPropInterface.jar \
vendor/sts/a04br3/proprietary/vendor/framework/mediatek-res/mediatek-res.apk:system/vendor/framework/mediatek-res/mediatek-res.apk \
vendor/sts/a04br3/proprietary/vendor/framework/oat/arm/CustomPropInterface.odex:system/vendor/framework/oat/arm/CustomPropInterface.odex \
vendor/sts/a04br3/proprietary/vendor/framework/oat/arm64/CustomPropInterface.odex:system/vendor/framework/oat/arm64/CustomPropInterface.odex \
vendor/sts/a04br3/proprietary/vendor/lib/egl/egl.cfg:system/vendor/lib/egl/egl.cfg \
vendor/sts/a04br3/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/audio.primary.mt8167.so:system/vendor/lib/hw/audio.primary.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/audio.r_submix.mt8167.so:system/vendor/lib/hw/audio.r_submix.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/audio.usb.mt8167.so:system/vendor/lib/hw/audio.usb.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/camera.mt8167.so:system/vendor/lib/hw/camera.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/gatekeeper.mt8167.so:system/vendor/lib/hw/gatekeeper.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/gralloc.mt8167.so:system/vendor/lib/hw/gralloc.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/hwcomposer.mt8167.so:system/vendor/lib/hw/hwcomposer.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/keystore.mt8167.so:system/vendor/lib/hw/keystore.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/lights.mt8167.so:system/vendor/lib/hw/lights.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/memtrack.mt8167.so:system/vendor/lib/hw/memtrack.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/sensors.mt8167.so:system/vendor/lib/hw/sensors.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/hw/vulkan.mt8167.so:system/vendor/lib/hw/vulkan.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib/lib3a.so:system/vendor/lib/lib3a.so \
vendor/sts/a04br3/proprietary/vendor/lib/lib_uree_mtk_video_secure_al.so:system/vendor/lib/lib_uree_mtk_video_secure_al.so \
vendor/sts/a04br3/proprietary/vendor/lib/libacdk.so:system/vendor/lib/libacdk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaed.so:system/vendor/lib/libaed.so \
vendor/sts/a04br3/proprietary/vendor/lib/libamr_wrap.so:system/vendor/lib/libamr_wrap.so \
vendor/sts/a04br3/proprietary/vendor/lib/libamrvt.so:system/vendor/lib/libamrvt.so \
vendor/sts/a04br3/proprietary/vendor/lib/libatvctrlservice.so:system/vendor/lib/libatvctrlservice.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudio_param_parser.so:system/vendor/lib/libaudio_param_parser.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiocompensationfilter.so:system/vendor/lib/libaudiocompensationfilter.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiocomponentengine.so:system/vendor/lib/libaudiocomponentengine.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiocustparam.so:system/vendor/lib/libaudiocustparam.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiodcrflt.so:system/vendor/lib/libaudiodcrflt.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiomtkdcremoval.so:system/vendor/lib/libaudiomtkdcremoval.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiosetting.so:system/vendor/lib/libaudiosetting.so \
vendor/sts/a04br3/proprietary/vendor/lib/libaudiotoolkit.so:system/vendor/lib/libaudiotoolkit.so \
vendor/sts/a04br3/proprietary/vendor/lib/libawb_wrap.so:system/vendor/lib/libawb_wrap.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbessound_hd_mtk.so:system/vendor/lib/libbessound_hd_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libblisrc.so:system/vendor/lib/libblisrc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libblisrc32.so:system/vendor/lib/libblisrc32.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_hw_test.so:system/vendor/lib/libbluetooth_hw_test.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_mtk.so:system/vendor/lib/libbluetooth_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_mtk_pure.so:system/vendor/lib/libbluetooth_mtk_pure.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbluetooth_relayer.so:system/vendor/lib/libbluetooth_relayer.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbluetoothem_mtk.so:system/vendor/lib/libbluetoothem_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libBnMtkCodec.so:system/vendor/lib/libBnMtkCodec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
vendor/sts/a04br3/proprietary/vendor/lib/libbwc.so:system/vendor/lib/libbwc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.camadapter.so:system/vendor/lib/libcam.camadapter.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.campipe.so:system/vendor/lib/libcam.campipe.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.camshot.so:system/vendor/lib/libcam.camshot.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.client.so:system/vendor/lib/libcam.client.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.device1.so:system/vendor/lib/libcam.device1.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.device3.so:system/vendor/lib/libcam.device3.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.exif.so:system/vendor/lib/libcam.exif.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.exif.v3.so:system/vendor/lib/libcam.exif.v3.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.hal3a.v3.dng.so:system/vendor/lib/libcam.hal3a.v3.dng.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.hal3a.v3.so:system/vendor/lib/libcam.hal3a.v3.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.halsensor.so:system/vendor/lib/libcam.halsensor.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.iopipe.so:system/vendor/lib/libcam.iopipe.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.iopipe_FrmB.so:system/vendor/lib/libcam.iopipe_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.metadata.so:system/vendor/lib/libcam.metadata.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.metadataprovider.so:system/vendor/lib/libcam.metadataprovider.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.paramsmgr.so:system/vendor/lib/libcam.paramsmgr.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.utils.sensorlistener.so:system/vendor/lib/libcam.utils.sensorlistener.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam.utils.so:system/vendor/lib/libcam.utils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam1_utils.so:system/vendor/lib/libcam1_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam3_app.so:system/vendor/lib/libcam3_app.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam3_hwnode.so:system/vendor/lib/libcam3_hwnode.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam3_hwpipeline.so:system/vendor/lib/libcam3_hwpipeline.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam3_pipeline.so:system/vendor/lib/libcam3_pipeline.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam3_utils.so:system/vendor/lib/libcam3_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam_hwutils.so:system/vendor/lib/libcam_hwutils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam_mmp.so:system/vendor/lib/libcam_mmp.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam_platform.so:system/vendor/lib/libcam_platform.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcam_utils.so:system/vendor/lib/libcam_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcamalgo.so:system/vendor/lib/libcamalgo.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcamdrv.so:system/vendor/lib/libcamdrv.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcamdrv_FrmB.so:system/vendor/lib/libcamdrv_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcameracustom.so:system/vendor/lib/libcameracustom.so \
vendor/sts/a04br3/proprietary/vendor/lib/libccci_util.so:system/vendor/lib/libccci_util.so \
vendor/sts/a04br3/proprietary/vendor/lib/libclangIMG.so:system/vendor/lib/libclangIMG.so \
vendor/sts/a04br3/proprietary/vendor/lib/libClearMotionFW.so:system/vendor/lib/libClearMotionFW.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcomutils.so:system/vendor/lib/libcomutils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcustom_jni.so:system/vendor/lib/libcustom_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcustom_nvram.so:system/vendor/lib/libcustom_nvram.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcustom_prop.so:system/vendor/lib/libcustom_prop.so \
vendor/sts/a04br3/proprietary/vendor/lib/libcvsd_mtk.so:system/vendor/lib/libcvsd_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libdirect-coredump.so:system/vendor/lib/libdirect-coredump.so \
vendor/sts/a04br3/proprietary/vendor/lib/libdpframework.so:system/vendor/lib/libdpframework.so \
vendor/sts/a04br3/proprietary/vendor/lib/libfeatureio.so:system/vendor/lib/libfeatureio.so \
vendor/sts/a04br3/proprietary/vendor/lib/libfeatureiodrv.so:system/vendor/lib/libfeatureiodrv.so \
vendor/sts/a04br3/proprietary/vendor/lib/libfile_op.so:system/vendor/lib/libfile_op.so \
vendor/sts/a04br3/proprietary/vendor/lib/libfmjni.so:system/vendor/lib/libfmjni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libfpspolicy.so:system/vendor/lib/libfpspolicy.so \
vendor/sts/a04br3/proprietary/vendor/lib/libgas.so:system/vendor/lib/libgas.so \
vendor/sts/a04br3/proprietary/vendor/lib/libGdmaScalerPipe.so:system/vendor/lib/libGdmaScalerPipe.so \
vendor/sts/a04br3/proprietary/vendor/lib/libged.so:system/vendor/lib/libged.so \
vendor/sts/a04br3/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
vendor/sts/a04br3/proprietary/vendor/lib/libgpu_aux.so:system/vendor/lib/libgpu_aux.so \
vendor/sts/a04br3/proprietary/vendor/lib/libgralloc_extra.so:system/vendor/lib/libgralloc_extra.so \
vendor/sts/a04br3/proprietary/vendor/lib/libgui_ext.so:system/vendor/lib/libgui_ext.so \
vendor/sts/a04br3/proprietary/vendor/lib/libhdrproc.so:system/vendor/lib/libhdrproc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libherope_sa.ca7.so:system/vendor/lib/libherope_sa.ca7.so \
vendor/sts/a04br3/proprietary/vendor/lib/libhevce_sb.ca7.android.so:system/vendor/lib/libhevce_sb.ca7.android.so \
vendor/sts/a04br3/proprietary/vendor/lib/libhwm.so:system/vendor/lib/libhwm.so \
vendor/sts/a04br3/proprietary/vendor/lib/libhwr_u_jni.so:system/vendor/lib/libhwr_u_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimageio.so:system/vendor/lib/libimageio.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimageio_FrmB.so:system/vendor/lib/libimageio_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimageio_plat_drv.so:system/vendor/lib/libimageio_plat_drv.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimageio_plat_drv_FrmB.so:system/vendor/lib/libimageio_plat_drv_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimsma.so:system/vendor/lib/libimsma.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimsma_rtp.so:system/vendor/lib/libimsma_rtp.so \
vendor/sts/a04br3/proprietary/vendor/lib/libimsma_socketwrapper.so:system/vendor/lib/libimsma_socketwrapper.so \
vendor/sts/a04br3/proprietary/vendor/lib/libion_mtk.so:system/vendor/lib/libion_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libjni_pq.so:system/vendor/lib/libjni_pq.so \
vendor/sts/a04br3/proprietary/vendor/lib/libJpgDecPipe.so:system/vendor/lib/libJpgDecPipe.so \
vendor/sts/a04br3/proprietary/vendor/lib/libJpgEncPipe.so:system/vendor/lib/libJpgEncPipe.so \
vendor/sts/a04br3/proprietary/vendor/lib/liblic_divx.so:system/vendor/lib/liblic_divx.so \
vendor/sts/a04br3/proprietary/vendor/lib/liblic_s263.so:system/vendor/lib/liblic_s263.so \
vendor/sts/a04br3/proprietary/vendor/lib/libLLVMIMG.so:system/vendor/lib/libLLVMIMG.so \
vendor/sts/a04br3/proprietary/vendor/lib/libm4u.so:system/vendor/lib/libm4u.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal.so:system/vendor/lib/libmal.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_datamngr.so:system/vendor/lib/libmal_datamngr.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_epdga.so:system/vendor/lib/libmal_epdga.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_imsmngr.so:system/vendor/lib/libmal_imsmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_mdmngr.so:system/vendor/lib/libmal_mdmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_nwmngr.so:system/vendor/lib/libmal_nwmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_rds.so:system/vendor/lib/libmal_rds.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_rilproxy.so:system/vendor/lib/libmal_rilproxy.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmal_simmngr.so:system/vendor/lib/libmal_simmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmatv_cust.so:system/vendor/lib/libmatv_cust.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmdfx.so:system/vendor/lib/libmdfx.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmemorydumper.so:system/vendor/lib/libmemorydumper.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmemtrack_GL.so:system/vendor/lib/libmemtrack_GL.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmhalImageCodec.so:system/vendor/lib/libmhalImageCodec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libminiui.so:system/vendor/lib/libminiui.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMiraVision_jni.so:system/vendor/lib/libMiraVision_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmjcFakeEngine.so:system/vendor/lib/libmjcFakeEngine.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmmprofile.so:system/vendor/lib/libmmprofile.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmmprofile_jni.so:system/vendor/lib/libmmprofile_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmmsdkservice.so:system/vendor/lib/libmmsdkservice.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmp4enc_sa.ca7.so:system/vendor/lib/libmp4enc_sa.ca7.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmrdump.so:system/vendor/lib/libmrdump.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmsbc_mtk.so:system/vendor/lib/libmsbc_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtcloader.so:system/vendor/lib/libmtcloader.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtk_drvb.so:system/vendor/lib/libmtk_drvb.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtk_mmutils.so:system/vendor/lib/libmtk_mmutils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_service.so:system/vendor/lib/libmtk_vt_service.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_swip.so:system/vendor/lib/libmtk_vt_swip.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_utils.so:system/vendor/lib/libmtk_vt_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtk_vt_wrapper.so:system/vendor/lib/libmtk_vt_wrapper.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtkcam_fwkutils.so:system/vendor/lib/libmtkcam_fwkutils.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtkjpeg.so:system/vendor/lib/libmtkjpeg.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtklimiter.so:system/vendor/lib/libmtklimiter.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxAdpcmDec.so:system/vendor/lib/libMtkOmxAdpcmDec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxAdpcmEnc.so:system/vendor/lib/libMtkOmxAdpcmEnc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxAlacDec.so:system/vendor/lib/libMtkOmxAlacDec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxApeDec.so:system/vendor/lib/libMtkOmxApeDec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxCore.so:system/vendor/lib/libMtkOmxCore.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxFlacDec.so:system/vendor/lib/libMtkOmxFlacDec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxG711Dec.so:system/vendor/lib/libMtkOmxG711Dec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxGsmDec.so:system/vendor/lib/libMtkOmxGsmDec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxMp3Dec.so:system/vendor/lib/libMtkOmxMp3Dec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxRawDec.so:system/vendor/lib/libMtkOmxRawDec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxVdecEx.so:system/vendor/lib/libMtkOmxVdecEx.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxVenc.so:system/vendor/lib/libMtkOmxVenc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libMtkOmxVorbisEnc.so:system/vendor/lib/libMtkOmxVorbisEnc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtkplayer.so:system/vendor/lib/libmtkplayer.so \
vendor/sts/a04br3/proprietary/vendor/lib/libmtkshifter.so:system/vendor/lib/libmtkshifter.so \
vendor/sts/a04br3/proprietary/vendor/lib/libnativecheck-jni.so:system/vendor/lib/libnativecheck-jni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libnvram.so:system/vendor/lib/libnvram.so \
vendor/sts/a04br3/proprietary/vendor/lib/libnvram_daemon_callback.so:system/vendor/lib/libnvram_daemon_callback.so \
vendor/sts/a04br3/proprietary/vendor/lib/libnvram_platform.so:system/vendor/lib/libnvram_platform.so \
vendor/sts/a04br3/proprietary/vendor/lib/libnvram_sec.so:system/vendor/lib/libnvram_sec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libnvramagentclient.so:system/vendor/lib/libnvramagentclient.so \
vendor/sts/a04br3/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
vendor/sts/a04br3/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
vendor/sts/a04br3/proprietary/vendor/lib/libperfservice.so:system/vendor/lib/libperfservice.so \
vendor/sts/a04br3/proprietary/vendor/lib/libperfservicenative.so:system/vendor/lib/libperfservicenative.so \
vendor/sts/a04br3/proprietary/vendor/lib/libpq_cust.so:system/vendor/lib/libpq_cust.so \
vendor/sts/a04br3/proprietary/vendor/lib/libpq_prot.so:system/vendor/lib/libpq_prot.so \
vendor/sts/a04br3/proprietary/vendor/lib/libPQDCjni.so:system/vendor/lib/libPQDCjni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libPQjni.so:system/vendor/lib/libPQjni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libpqservice.so:system/vendor/lib/libpqservice.so \
vendor/sts/a04br3/proprietary/vendor/lib/libprogrambinary.so:system/vendor/lib/libprogrambinary.so \
vendor/sts/a04br3/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
vendor/sts/a04br3/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
vendor/sts/a04br3/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
vendor/sts/a04br3/proprietary/vendor/lib/libratconfig.so:system/vendor/lib/libratconfig.so \
vendor/sts/a04br3/proprietary/vendor/lib/librilmtk.so:system/vendor/lib/librilmtk.so \
vendor/sts/a04br3/proprietary/vendor/lib/librilproxy.so:system/vendor/lib/librilproxy.so \
vendor/sts/a04br3/proprietary/vendor/lib/librilproxyutils.so:system/vendor/lib/librilproxyutils.so \
vendor/sts/a04br3/proprietary/vendor/lib/librrc.so:system/vendor/lib/librrc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libsbox.so:system/vendor/lib/libsbox.so \
vendor/sts/a04br3/proprietary/vendor/lib/libshowlogo.so:system/vendor/lib/libshowlogo.so \
vendor/sts/a04br3/proprietary/vendor/lib/libsink.so:system/vendor/lib/libsink.so \
vendor/sts/a04br3/proprietary/vendor/lib/libsource.so:system/vendor/lib/libsource.so \
vendor/sts/a04br3/proprietary/vendor/lib/libspeech_enh_lib.so:system/vendor/lib/libspeech_enh_lib.so \
vendor/sts/a04br3/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
vendor/sts/a04br3/proprietary/vendor/lib/libstagefrighthw.so:system/vendor/lib/libstagefrighthw.so \
vendor/sts/a04br3/proprietary/vendor/lib/libstorage_otp.so:system/vendor/lib/libstorage_otp.so \
vendor/sts/a04br3/proprietary/vendor/lib/libSwJpgCodec.so:system/vendor/lib/libSwJpgCodec.so \
vendor/sts/a04br3/proprietary/vendor/lib/libsysenv.so:system/vendor/lib/libsysenv.so \
vendor/sts/a04br3/proprietary/vendor/lib/libtimestretch.so:system/vendor/lib/libtimestretch.so \
vendor/sts/a04br3/proprietary/vendor/lib/libtouchfilter.so:system/vendor/lib/libtouchfilter.so \
vendor/sts/a04br3/proprietary/vendor/lib/libts.so:system/vendor/lib/libts.so \
vendor/sts/a04br3/proprietary/vendor/lib/libtz_uree.so:system/vendor/lib/libtz_uree.so \
vendor/sts/a04br3/proprietary/vendor/lib/libudf.so:system/vendor/lib/libudf.so \
vendor/sts/a04br3/proprietary/vendor/lib/libufwriter.so:system/vendor/lib/libufwriter.so \
vendor/sts/a04br3/proprietary/vendor/lib/libui_ext.so:system/vendor/lib/libui_ext.so \
vendor/sts/a04br3/proprietary/vendor/lib/liburee_meta_drmkeyinstall_v2.so:system/vendor/lib/liburee_meta_drmkeyinstall_v2.so \
vendor/sts/a04br3/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvc1dec_sa.ca7.so:system/vendor/lib/libvc1dec_sa.ca7.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvcodec_cap.so:system/vendor/lib/libvcodec_cap.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvcodec_oal.so:system/vendor/lib/libvcodec_oal.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvcodec_utility.so:system/vendor/lib/libvcodec_utility.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvcodecdrv.so:system/vendor/lib/libvcodecdrv.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvoicerecognition.so:system/vendor/lib/libvoicerecognition.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvoicerecognition_jni.so:system/vendor/lib/libvoicerecognition_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvp8dec_sa.ca7.so:system/vendor/lib/libvp8dec_sa.ca7.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvp8enc_sa.ca7.so:system/vendor/lib/libvp8enc_sa.ca7.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvp9dec_sa.ca7.so:system/vendor/lib/libvp9dec_sa.ca7.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvt_avsync.so:system/vendor/lib/libvt_avsync.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvt_custom.so:system/vendor/lib/libvt_custom.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvt_socketbind.so:system/vendor/lib/libvt_socketbind.so \
vendor/sts/a04br3/proprietary/vendor/lib/libvtmal.so:system/vendor/lib/libvtmal.so \
vendor/sts/a04br3/proprietary/vendor/lib/libwidevinehdcpinfo.so:system/vendor/lib/libwidevinehdcpinfo.so \
vendor/sts/a04br3/proprietary/vendor/lib/libyv12util.so:system/vendor/lib/libyv12util.so \
vendor/sts/a04br3/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
vendor/sts/a04br3/proprietary/vendor/lib/mtk-ril.so:system/vendor/lib/mtk-ril.so \
vendor/sts/a04br3/proprietary/vendor/lib/mtk-rilproxy.so:system/vendor/lib/mtk-rilproxy.so \
vendor/sts/a04br3/proprietary/vendor/lib64/egl/libEGL_mtk.so:system/vendor/lib64/egl/libEGL_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/egl/libGLESv1_CM_mtk.so:system/vendor/lib64/egl/libGLESv1_CM_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/egl/libGLESv2_mtk.so:system/vendor/lib64/egl/libGLESv2_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/audio.primary.mt8167.so:system/vendor/lib64/hw/audio.primary.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/audio.r_submix.mt8167.so:system/vendor/lib64/hw/audio.r_submix.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/audio.usb.mt8167.so:system/vendor/lib64/hw/audio.usb.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/camera.mt8167.so:system/vendor/lib64/hw/camera.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/gatekeeper.mt8167.so:system/vendor/lib64/hw/gatekeeper.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/gralloc.mt8167.so:system/vendor/lib64/hw/gralloc.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/hwcomposer.mt8167.so:system/vendor/lib64/hw/hwcomposer.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/keystore.mt8167.so:system/vendor/lib64/hw/keystore.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/lights.mt8167.so:system/vendor/lib64/hw/lights.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/memtrack.mt8167.so:system/vendor/lib64/hw/memtrack.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/sensors.mt8167.so:system/vendor/lib64/hw/sensors.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/hw/vulkan.mt8167.so:system/vendor/lib64/hw/vulkan.mt8167.so \
vendor/sts/a04br3/proprietary/vendor/lib64/lib3a.so:system/vendor/lib64/lib3a.so \
vendor/sts/a04br3/proprietary/vendor/lib64/lib_uree_mtk_video_secure_al.so:system/vendor/lib64/lib_uree_mtk_video_secure_al.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libacdk.so:system/vendor/lib64/libacdk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaed.so:system/vendor/lib64/libaed.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libatvctrlservice.so:system/vendor/lib64/libatvctrlservice.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudio_param_parser.so:system/vendor/lib64/libaudio_param_parser.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudiocompensationfilter.so:system/vendor/lib64/libaudiocompensationfilter.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudiocomponentengine.so:system/vendor/lib64/libaudiocomponentengine.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudiocustparam.so:system/vendor/lib64/libaudiocustparam.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudiodcrflt.so:system/vendor/lib64/libaudiodcrflt.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudiosetting.so:system/vendor/lib64/libaudiosetting.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libaudiotoolkit.so:system/vendor/lib64/libaudiotoolkit.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbessound_hd_mtk.so:system/vendor/lib64/libbessound_hd_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libblisrc.so:system/vendor/lib64/libblisrc.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libblisrc32.so:system/vendor/lib64/libblisrc32.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_hw_test.so:system/vendor/lib64/libbluetooth_hw_test.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_mtk.so:system/vendor/lib64/libbluetooth_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_mtk_pure.so:system/vendor/lib64/libbluetooth_mtk_pure.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbluetooth_relayer.so:system/vendor/lib64/libbluetooth_relayer.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbluetoothem_mtk.so:system/vendor/lib64/libbluetoothem_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libBnMtkCodec.so:system/vendor/lib64/libBnMtkCodec.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libbwc.so:system/vendor/lib64/libbwc.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.camadapter.so:system/vendor/lib64/libcam.camadapter.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.campipe.so:system/vendor/lib64/libcam.campipe.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.camshot.so:system/vendor/lib64/libcam.camshot.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.client.so:system/vendor/lib64/libcam.client.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.device1.so:system/vendor/lib64/libcam.device1.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.device3.so:system/vendor/lib64/libcam.device3.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.exif.so:system/vendor/lib64/libcam.exif.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.exif.v3.so:system/vendor/lib64/libcam.exif.v3.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.hal3a.v3.dng.so:system/vendor/lib64/libcam.hal3a.v3.dng.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.hal3a.v3.so:system/vendor/lib64/libcam.hal3a.v3.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.halsensor.so:system/vendor/lib64/libcam.halsensor.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.iopipe.so:system/vendor/lib64/libcam.iopipe.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.iopipe_FrmB.so:system/vendor/lib64/libcam.iopipe_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.metadata.so:system/vendor/lib64/libcam.metadata.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.metadataprovider.so:system/vendor/lib64/libcam.metadataprovider.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.paramsmgr.so:system/vendor/lib64/libcam.paramsmgr.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.utils.sensorlistener.so:system/vendor/lib64/libcam.utils.sensorlistener.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam.utils.so:system/vendor/lib64/libcam.utils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam1_utils.so:system/vendor/lib64/libcam1_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_app.so:system/vendor/lib64/libcam3_app.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_hwnode.so:system/vendor/lib64/libcam3_hwnode.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_hwpipeline.so:system/vendor/lib64/libcam3_hwpipeline.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_pipeline.so:system/vendor/lib64/libcam3_pipeline.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam3_utils.so:system/vendor/lib64/libcam3_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam_hwutils.so:system/vendor/lib64/libcam_hwutils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam_mmp.so:system/vendor/lib64/libcam_mmp.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam_platform.so:system/vendor/lib64/libcam_platform.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcam_utils.so:system/vendor/lib64/libcam_utils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcamalgo.so:system/vendor/lib64/libcamalgo.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcamdrv.so:system/vendor/lib64/libcamdrv.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcamdrv_FrmB.so:system/vendor/lib64/libcamdrv_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcameracustom.so:system/vendor/lib64/libcameracustom.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libccci_util.so:system/vendor/lib64/libccci_util.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libclangIMG.so:system/vendor/lib64/libclangIMG.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcomutils.so:system/vendor/lib64/libcomutils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcustom_jni.so:system/vendor/lib64/libcustom_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcustom_nvram.so:system/vendor/lib64/libcustom_nvram.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcustom_prop.so:system/vendor/lib64/libcustom_prop.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libcvsd_mtk.so:system/vendor/lib64/libcvsd_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libdirect-coredump.so:system/vendor/lib64/libdirect-coredump.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libdpframework.so:system/vendor/lib64/libdpframework.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libfeatureio.so:system/vendor/lib64/libfeatureio.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libfeatureiodrv.so:system/vendor/lib64/libfeatureiodrv.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libfile_op.so:system/vendor/lib64/libfile_op.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libfmjni.so:system/vendor/lib64/libfmjni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libfpspolicy.so:system/vendor/lib64/libfpspolicy.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libgas.so:system/vendor/lib64/libgas.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libGdmaScalerPipe.so:system/vendor/lib64/libGdmaScalerPipe.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libged.so:system/vendor/lib64/libged.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libglslcompiler.so:system/vendor/lib64/libglslcompiler.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libgpu_aux.so:system/vendor/lib64/libgpu_aux.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libgralloc_extra.so:system/vendor/lib64/libgralloc_extra.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libgui_ext.so:system/vendor/lib64/libgui_ext.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libhdrproc.so:system/vendor/lib64/libhdrproc.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libhwm.so:system/vendor/lib64/libhwm.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libhwr_u_jni.so:system/vendor/lib64/libhwr_u_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimageio.so:system/vendor/lib64/libimageio.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimageio_FrmB.so:system/vendor/lib64/libimageio_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimageio_plat_drv.so:system/vendor/lib64/libimageio_plat_drv.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimageio_plat_drv_FrmB.so:system/vendor/lib64/libimageio_plat_drv_FrmB.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libIMGegl.so:system/vendor/lib64/libIMGegl.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimsma.so:system/vendor/lib64/libimsma.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimsma_rtp.so:system/vendor/lib64/libimsma_rtp.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libimsma_socketwrapper.so:system/vendor/lib64/libimsma_socketwrapper.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libion_mtk.so:system/vendor/lib64/libion_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libjni_pq.so:system/vendor/lib64/libjni_pq.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libJpgDecPipe.so:system/vendor/lib64/libJpgDecPipe.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libJpgEncPipe.so:system/vendor/lib64/libJpgEncPipe.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libLLVMIMG.so:system/vendor/lib64/libLLVMIMG.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libm4u.so:system/vendor/lib64/libm4u.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal.so:system/vendor/lib64/libmal.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_datamngr.so:system/vendor/lib64/libmal_datamngr.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_epdga.so:system/vendor/lib64/libmal_epdga.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_imsmngr.so:system/vendor/lib64/libmal_imsmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_mdmngr.so:system/vendor/lib64/libmal_mdmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_nwmngr.so:system/vendor/lib64/libmal_nwmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_rds.so:system/vendor/lib64/libmal_rds.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_rilproxy.so:system/vendor/lib64/libmal_rilproxy.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmal_simmngr.so:system/vendor/lib64/libmal_simmngr.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmatv_cust.so:system/vendor/lib64/libmatv_cust.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmdfx.so:system/vendor/lib64/libmdfx.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmemorydumper.so:system/vendor/lib64/libmemorydumper.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmemtrack_GL.so:system/vendor/lib64/libmemtrack_GL.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmhalImageCodec.so:system/vendor/lib64/libmhalImageCodec.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libminiui.so:system/vendor/lib64/libminiui.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libMiraVision_jni.so:system/vendor/lib64/libMiraVision_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmmprofile.so:system/vendor/lib64/libmmprofile.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmmprofile_jni.so:system/vendor/lib64/libmmprofile_jni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmrdump.so:system/vendor/lib64/libmrdump.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmsbc_mtk.so:system/vendor/lib64/libmsbc_mtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtk_drvb.so:system/vendor/lib64/libmtk_drvb.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtk_mmutils.so:system/vendor/lib64/libmtk_mmutils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtk_vt_wrapper.so:system/vendor/lib64/libmtk_vt_wrapper.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtkcam_fwkutils.so:system/vendor/lib64/libmtkcam_fwkutils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtkjpeg.so:system/vendor/lib64/libmtkjpeg.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtklimiter.so:system/vendor/lib64/libmtklimiter.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libMtkOmxCore.so:system/vendor/lib64/libMtkOmxCore.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtkplayer.so:system/vendor/lib64/libmtkplayer.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libmtkshifter.so:system/vendor/lib64/libmtkshifter.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libnativecheck-jni.so:system/vendor/lib64/libnativecheck-jni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libnvram.so:system/vendor/lib64/libnvram.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libnvram_daemon_callback.so:system/vendor/lib64/libnvram_daemon_callback.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libnvram_platform.so:system/vendor/lib64/libnvram_platform.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libnvram_sec.so:system/vendor/lib64/libnvram_sec.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libnvramagentclient.so:system/vendor/lib64/libnvramagentclient.so \
vendor/sts/a04br3/proprietary/vendor/lib64/liboclcompiler.so:system/vendor/lib64/liboclcompiler.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libperfservice.so:system/vendor/lib64/libperfservice.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libperfservicenative.so:system/vendor/lib64/libperfservicenative.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libpq_cust.so:system/vendor/lib64/libpq_cust.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libpq_prot.so:system/vendor/lib64/libpq_prot.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libPQDCjni.so:system/vendor/lib64/libPQDCjni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libPQjni.so:system/vendor/lib64/libPQjni.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libpqservice.so:system/vendor/lib64/libpqservice.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libprogrambinary.so:system/vendor/lib64/libprogrambinary.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libpvrANDROID_WSEGL.so:system/vendor/lib64/libpvrANDROID_WSEGL.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libPVROCL.so:system/vendor/lib64/libPVROCL.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libPVRScopeServices.so:system/vendor/lib64/libPVRScopeServices.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libratconfig.so:system/vendor/lib64/libratconfig.so \
vendor/sts/a04br3/proprietary/vendor/lib64/librilmtk.so:system/vendor/lib64/librilmtk.so \
vendor/sts/a04br3/proprietary/vendor/lib64/librilproxy.so:system/vendor/lib64/librilproxy.so \
vendor/sts/a04br3/proprietary/vendor/lib64/librilproxyutils.so:system/vendor/lib64/librilproxyutils.so \
vendor/sts/a04br3/proprietary/vendor/lib64/librrc.so:system/vendor/lib64/librrc.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libsbox.so:system/vendor/lib64/libsbox.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libsink.so:system/vendor/lib64/libsink.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libsource.so:system/vendor/lib64/libsource.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libspeech_enh_lib.so:system/vendor/lib64/libspeech_enh_lib.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libsrv_um.so:system/vendor/lib64/libsrv_um.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libstagefrighthw.so:system/vendor/lib64/libstagefrighthw.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libSwJpgCodec.so:system/vendor/lib64/libSwJpgCodec.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libsysenv.so:system/vendor/lib64/libsysenv.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libterservice.so:system/vendor/lib64/libterservice.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libtouchfilter.so:system/vendor/lib64/libtouchfilter.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libts.so:system/vendor/lib64/libts.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libtz_uree.so:system/vendor/lib64/libtz_uree.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libudf.so:system/vendor/lib64/libudf.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libufwriter.so:system/vendor/lib64/libufwriter.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libui_ext.so:system/vendor/lib64/libui_ext.so \
vendor/sts/a04br3/proprietary/vendor/lib64/liburee_meta_drmkeyinstall_v2.so:system/vendor/lib64/liburee_meta_drmkeyinstall_v2.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libusc.so:system/vendor/lib64/libusc.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libvcodec_cap.so:system/vendor/lib64/libvcodec_cap.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libvcodec_utility.so:system/vendor/lib64/libvcodec_utility.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libvcodecdrv.so:system/vendor/lib64/libvcodecdrv.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libvt_avsync.so:system/vendor/lib64/libvt_avsync.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libwidevinehdcpinfo.so:system/vendor/lib64/libwidevinehdcpinfo.so \
vendor/sts/a04br3/proprietary/vendor/lib64/libyv12util.so:system/vendor/lib64/libyv12util.so \
vendor/sts/a04br3/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
vendor/sts/a04br3/proprietary/vendor/lib64/mtk-ril.so:system/vendor/lib64/mtk-ril.so \
vendor/sts/a04br3/proprietary/vendor/lib64/mtk-rilproxy.so:system/vendor/lib64/mtk-rilproxy.so \
vendor/sts/a04br3/proprietary/vendor/plugin/FwkPlugin/FwkPlugin.apk:system/vendor/plugin/FwkPlugin/FwkPlugin.apk \
vendor/sts/a04br3/proprietary/vendor/plugin/FwkPlugin/FwkPlugin.mpinfo:system/vendor/plugin/FwkPlugin/FwkPlugin.mpinfo \
vendor/sts/a04br3/proprietary/vendor/plugin/FwkPlugin/oat/arm/FwkPlugin.odex:system/vendor/plugin/FwkPlugin/oat/arm/FwkPlugin.odex \
vendor/sts/a04br3/proprietary/vendor/plugin/FwkPlugin/oat/arm64/FwkPlugin.odex:system/vendor/plugin/FwkPlugin/oat/arm64/FwkPlugin.odex \
vendor/sts/a04br3/proprietary/vendor/plugin/Signatures/mplugin_guard.xml:system/vendor/plugin/Signatures/mplugin_guard.xml \
vendor/sts/a04br3/proprietary/vendor/res/images/lcd_test_00.png:system/vendor/res/images/lcd_test_00.png \
vendor/sts/a04br3/proprietary/vendor/res/images/lcd_test_01.png:system/vendor/res/images/lcd_test_01.png \
vendor/sts/a04br3/proprietary/vendor/res/images/lcd_test_02.png:system/vendor/res/images/lcd_test_02.png \
vendor/sts/a04br3/proprietary/vendor/res/sound/ringtone.wav:system/vendor/res/sound/ringtone.wav \
vendor/sts/a04br3/proprietary/vendor/res/sound/testpattern1.wav:system/vendor/res/sound/testpattern1.wav \
vendor/sts/a04br3/proprietary/usr/keychars/Generic.kcm:system/usr/keychars/Generic.kcm \
vendor/sts/a04br3/proprietary/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \
vendor/sts/a04br3/proprietary/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \
vendor/sts/a04br3/proprietary/usr/keychars/Vendor_18d1_Product_5018.kcm:system/usr/keychars/Vendor_18d1_Product_5018.kcm \
vendor/sts/a04br3/proprietary/usr/keychars/Virtual.kcm:system/usr/keychars/Virtual.kcm \
vendor/sts/a04br3/proprietary/usr/keylayout/ACCDET.kl:system/usr/keylayout/ACCDET.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_0079_Product_0011.kl:system/usr/keylayout/Vendor_0079_Product_0011.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_b501.kl:system/usr/keylayout/Vendor_046d_Product_b501.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c219.kl:system/usr/keylayout/Vendor_046d_Product_c219.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c21d.kl:system/usr/keylayout/Vendor_046d_Product_c21d.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c21f.kl:system/usr/keylayout/Vendor_046d_Product_c21f.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_0583_Product_2060.kl:system/usr/keylayout/Vendor_0583_Product_2060.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_0b05_Product_4500.kl:system/usr/keylayout/Vendor_0b05_Product_4500.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1038_Product_1412.kl:system/usr/keylayout/Vendor_1038_Product_1412.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_12bd_Product_d015.kl:system/usr/keylayout/Vendor_12bd_Product_d015.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1532_Product_0900.kl:system/usr/keylayout/Vendor_1532_Product_0900.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1689_Product_fd00.kl:system/usr/keylayout/Vendor_1689_Product_fd00.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1689_Product_fd01.kl:system/usr/keylayout/Vendor_1689_Product_fd01.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1689_Product_fe00.kl:system/usr/keylayout/Vendor_1689_Product_fe00.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_18d1_Product_2c40.kl:system/usr/keylayout/Vendor_18d1_Product_2c40.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_18d1_Product_5018.kl:system/usr/keylayout/Vendor_18d1_Product_5018.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1949_Product_0401.kl:system/usr/keylayout/Vendor_1949_Product_0401.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1bad_Product_f016.kl:system/usr/keylayout/Vendor_1bad_Product_f016.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1bad_Product_f023.kl:system/usr/keylayout/Vendor_1bad_Product_f023.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1bad_Product_f027.kl:system/usr/keylayout/Vendor_1bad_Product_f027.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1bad_Product_f036.kl:system/usr/keylayout/Vendor_1bad_Product_f036.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_1d79_Product_0009.kl:system/usr/keylayout/Vendor_1d79_Product_0009.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_2378_Product_1008.kl:system/usr/keylayout/Vendor_2378_Product_1008.kl \
vendor/sts/a04br3/proprietary/usr/keylayout/Vendor_2378_Product_100a.kl:system/usr/keylayout/Vendor_2378_Product_100a.kl \
vendor/sts/a04br3/proprietary/vendor/etc/mixer_paths.xml:system/etc/mixer_paths.xml
