PRODUCT_COPY_FILES += \
    vendor/sts/a04br3/proprietary/lib64/libRS.so:system/lib64/libRS.so \
    vendor/sts/a04br3/proprietary/lib64/libRS_internal.so:system/lib64/libRS_internal.so \
    vendor/sts/a04br3/proprietary/lib64/librs_jni.so:system/lib64/librs_jni.so \
    vendor/sts/a04br3/proprietary/lib64/libRScpp.so:system/lib64/libRScpp.so \
    vendor/sts/a04br3/proprietary/lib64/libRSCpuRef.so:system/lib64/libRSCpuRef.so \
    vendor/sts/a04br3/proprietary/lib64/libRSDriver.so:system/lib64/libRSDriver.so \
    vendor/sts/a04br3/proprietary/lib/libRS.so:system/lib/libRS.so \
    vendor/sts/a04br3/proprietary/lib/libRS_internal.so:system/lib/libRS_internal.so \
    vendor/sts/a04br3/proprietary/lib/librs_jni.so:system/lib/librs_jni.so \
    vendor/sts/a04br3/proprietary/lib/libRScpp.so:system/lib/libRScpp.so \
    vendor/sts/a04br3/proprietary/lib/libRSCpuRef.so:system/lib/libRSCpuRef.so \
    vendor/sts/a04br3/proprietary/lib/libRSDriver.so:system/lib/libRSDriver.so \
    vendor/sts/a04br3/proprietary/usr/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl \
    vendor/sts/a04br3/proprietary/lib64/libjni_eglfence.so:system/lib64/libjni_eglfence.so \
    vendor/sts/a04br3/proprietary/lib64/libja3m.so:system/lib64/libja3m.so \
    vendor/sts/a04br3/proprietary/lib64/libttspico.so:system/lib64/libttspico.so \
    vendor/sts/a04br3/proprietary/lib64/libjni_filtershow_filters.so:system/lib64/libjni_filtershow_filters.so \
    vendor/sts/a04br3/proprietary/lib64/libxml2.so:system/lib64/libxml2.so \
    vendor/sts/a04br3/proprietary/lib64/libjni_jpegstream.so:system/lib64/libjni_jpegstream.so \
    vendor/sts/a04br3/proprietary/lib64/libfs_mgr.so:system/lib64/libfs_mgr.so \
    vendor/sts/a04br3/proprietary/lib64/libttscompat.so:system/lib64/libttscompat.so \
    vendor/sts/a04br3/proprietary/lib64/libalsautils.so:system/lib64/libalsautils.so \
    vendor/sts/a04br3/proprietary/lib64/libmediatek_exceptionlog.so:system/lib64/libmediatek_exceptionlog.so \
    vendor/sts/a04br3/proprietary/lib64/hw/audio.usb.default.so:system/lib64/hw/audio.usb.default.so \
    vendor/sts/a04br3/proprietary/lib64/hw/audio_policy.stub.so:system/lib64/hw/audio_policy.stub.so \
    vendor/sts/a04br3/proprietary/lib64/egl/libGLES_android.so:system/lib64/egl/libGLES_android.so \
    vendor/sts/a04br3/proprietary/lib/libjni_eglfence.so:system/lib/libjni_eglfence.so \
    vendor/sts/a04br3/proprietary/lib/libja3m.so:system/lib/libja3m.so \
    vendor/sts/a04br3/proprietary/lib/libext2_blkid.so:system/lib/libext2_blkid.so \
    vendor/sts/a04br3/proprietary/lib/libext2_uuid.so:system/lib/libext2_uuid.so \
    vendor/sts/a04br3/proprietary/lib/libMTKAudioTimeStretch.so:system/lib/libMTKAudioTimeStretch.so \
    vendor/sts/a04br3/proprietary/lib/libjni_filtershow_filters.so:system/lib/libjni_filtershow_filters.so \
    vendor/sts/a04br3/proprietary/lib/libxml2.so:system/lib/libxml2.so \
    vendor/sts/a04br3/proprietary/lib/libext2_com_err.so:system/lib/libext2_com_err.so \
    vendor/sts/a04br3/proprietary/lib/libjni_jpegstream.so:system/lib/libjni_jpegstream.so \
    vendor/sts/a04br3/proprietary/lib/libfs_mgr.so:system/lib/libfs_mgr.so \
    vendor/sts/a04br3/proprietary/lib/libalsautils.so:system/lib/libalsautils.so \
    vendor/sts/a04br3/proprietary/lib/libmediatek_exceptionlog.so:system/lib/libmediatek_exceptionlog.so \
    vendor/sts/a04br3/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/sts/a04br3/proprietary/lib/hw/audio_policy.stub.so:system/lib/hw/audio_policy.stub.so \
    vendor/sts/a04br3/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/sts/a04br3/proprietary/lib/libext2_e2p.so:system/lib/libext2_e2p.so \
    vendor/sts/a04br3/proprietary/lib/libext2fs.so:system/lib/libext2fs.so \
    vendor/sts/a04br3/proprietary/lib/libext2_profile.so:system/lib/libext2_profile.so 
