name: Check Vendor Blobs and Generate Unregistered Files Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-blobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Copy files to vendor/sts/a04br3
        run: |
          mkdir -p vendor/sts/a04br3/proprietary
          echo "Files copied or already in place."

      - name: Extract registered files from .mk and list repo files
        run: |
          cat <<EOF > check_blobs.py
          import os
          import re

          mk_file = 'a04br3-vendor-blobs.mk.txt'

          repo_dir = 'vendor/sts/a04br3/proprietary'

          registered = set()
          with open(mk_file, 'r') as f:
              for line in f:
                  line = line.strip()
                  if line.startswith('vendor/sts/a04br3/proprietary/') and ':' in line:
                      path = line.split(':')[0].rstrip(' \\')
                      registered.add(path.replace('vendor/sts/a04br3/proprietary/', ''))

          repo_files = set()
          for root, dirs, files in os.walk(repo_dir):
              for file in files:
                  full_path = os.path.join(root, file)
                  rel_path = os.path.relpath(full_path, repo_dir)
                  repo_files.add(rel_path)

          unregistered = repo_files - registered
          unregistered_count = len(unregistered)

          with open('unregistered_files.txt', 'w') as out:
              out.write(f"Total files in repository directory: {len(repo_files)}\n")
              out.write(f"Registered in .mk: {len(registered)}\n")
              out.write(f"Unregistered count: {unregistered_count}\n\n")
              out.write("Unregistered files:\n")
              for file in sorted(unregistered):
                  out.write(f"{file}\n")

          print(f"Unregistered files saved to unregistered_files.txt")
          print(f"Total repo files: {len(repo_files)}")
          print(f"Matches .mk registered: {len(registered) == len(repo_files)}")
          EOF

          python check_blobs.py

      - name: Upload report to artifact
        uses: actions/upload-artifact@v4
        with:
          name: unregistered-files-report
          path: unregistered_files.txt

      - name: Create Release and Upload Report
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Vendor Blobs Check Report ${{ github.run_number }}
          body: |
            Automated check of vendor blobs against .mk file.
            See attached unregistered_files.txt for details.
          draft: false
          prerelease: false

      - name: Upload Report to Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: unregistered_files.txt
          asset_name: unregistered_files.txt
          asset_content_type: text/plain
